import { db } from "../config/db.js";
import { coustomeRecipesTable } from "./schema.js";
import { sql } from "drizzle-orm";

const rawData = `Andhra Pradesh,Hyderabadi Biryani,https://www.google.com/search?tbm=isch&q=Hyderabadi+Biryani,60 mins,"Basmati Rice; Chicken/Mutton; Yogurt; Onions; Spices; Saffron",400 kcal,"[""Wash the chicken/mutton thoroughly and drain excess water."", ""In a large bowl, mix meat with ginger-garlic paste, turmeric, red chili powder, yogurt, lemon juice, fried onions (birista), chopped mint, coriander, and salt. Marinate for at least 4 hours or overnight."", ""Wash basmati rice and soak it for 30 minutes."", ""Boil a large pot of water with whole spices (bay leaf, cloves, cardamom, shahi jeera) and salt. Add the soaked rice."", ""Cook the rice until it is 70% done (grains should still have a slight bite). Drain the water."", ""In a heavy-bottomed pan (Handi), spread the marinated meat in an even layer at the bottom."", ""Layer the 70% cooked rice over the meat. Do not mix."", ""Sprinkle saffron milk, ghee, remaining fried onions, and mint leaves on top of the rice."", ""Seal the pot with dough or a tight lid/foil to trap steam (Dum cooking)."", ""Cook on high heat for 10 minutes, then lower the heat to the minimum and cook for 40-45 minutes."", ""Turn off heat and let it rest for 15 minutes before opening. Serve hot.""]"
Andhra Pradesh,Gongura Mutton,https://www.google.com/search?tbm=isch&q=Gongura+Mutton+Curry,50 mins,"Mutton; Gongura Leaves (Sorrel); Onions; Green Chilies; Ginger-Garlic Paste",350 kcal,"[""Wash the mutton pieces and pressure cook them with chopped onions, ginger-garlic paste, turmeric, and a little water for 4-5 whistles until soft."", ""Pick the Gongura (sorrel) leaves and wash them well. discard stems."", ""In a pan, heat a little oil and fry the Gongura leaves and green chilies until the leaves shrink and become mushy. Let it cool."", ""Grind the fried Gongura leaves into a coarse paste."", ""In a separate kadhai, heat oil. Add cloves, cardamom, and sliced onions. Sauté until onions turn golden."", ""Add the cooked mutton (keep the stock/water separate) and fry for 5 minutes."", ""Add red chili powder, coriander powder, and salt. Mix well."", ""Add the Gongura paste to the mutton and mix thoroughly."", ""Pour in the leftover mutton stock (water from pressure cooker). adjust consistency."", ""Cover and simmer on low heat for 10-15 minutes until oil floats on top."", ""Serve hot with steamed rice.""]"
Andhra Pradesh,Pesarattu (Green Moong Dosa),https://www.google.com/search?tbm=isch&q=Pesarattu+Dosa,20 mins,"Whole Green Moong Dal; Rice; Ginger; Green Chilies; Cumin; Onions",200 kcal,"[""Wash whole green moong dal and raw rice thoroughly. Soak them together in water for 4 to 6 hours (or overnight)."", ""Drain the water. Transfer the soaked dal and rice into a grinder."", ""Add green chilies, ginger pieces, and cumin seeds into the grinder."", ""Grind to a smooth batter adding very little water. The consistency should be like dosa batter (not too runny)."", ""Add salt to the batter and mix well. (No fermentation is needed, you can use it immediately)."", ""Heat a tawa (griddle) on medium heat. Sprinkle some water and wipe it clean."", ""Pour a ladle full of batter in the center and spread it in a circular motion to make a thin dosa."", ""Drizzle 1 teaspoon of oil around the edges."", ""Sprinkle chopped onions, chopped ginger, and cumin seeds on top of the dosa while it is cooking."", ""Press the onions gently with a spatula so they stick."", ""Cook until the bottom turns golden and crisp. Flip if you like crispier onions, or fold and remove."", ""Serve hot with Upma (optional) and Ginger Chutney.""]"
Andhra Pradesh,Gutti Vankaya Kura (Stuffed Brinjal),https://www.google.com/search?tbm=isch&q=Gutti+Vankaya+Curry,40 mins,"Small Brinjals; Peanuts; Coconut; Sesame Seeds; Tamarind; Onions",280 kcal,"[""Dry roast peanuts, sesame seeds, coriander seeds, cumin seeds, dried coconut, cinnamon, and cloves until aromatic. Cool and grind into a fine powder."", ""Add onion pieces, ginger, garlic, tamarind, and salt to the blender with the spice powder. Grind to a smooth paste adding a little water."", ""Wash small purple brinjals. Slit them in a 'plus' (+) shape from the bottom, keeping the stem intact (don't cut fully)."", ""Stuff the ground masala paste inside each brinjal tightly. Keep remaining paste aside."", ""Heat oil in a deep pan. Add mustard seeds and curry leaves. Let them splutter."", ""Gently place the stuffed brinjals in the oil. Fry them for 5-8 minutes, turning occasionally until the skin blisters slightly."", ""Add the remaining masala paste to the pan and mix gently."", ""Add about 1 cup of water and salt as needed. Bring to a boil."", ""Cover the pan with a lid and cook on low-medium heat for 15-20 minutes."", ""Cook until the brinjals are completely soft and oil separates from the gravy."", ""Garnish with coriander leaves.""]"
Andhra Pradesh,Chepala Pulusu (Fish Curry),https://www.google.com/search?tbm=isch&q=Andhra+Chepala+Pulusu,45 mins,"Fish Pieces; Tamarind Pulp; Onions; Tomatoes; Mustard Seeds; Fenugreek",300 kcal,"[""Soak lemon-sized tamarind in warm water and extract the thick juice (pulp). Discard the fiber."", ""Wash fish pieces carefully with salt and turmeric water. Drain well."", ""Heat oil in a wide, flat pan (fish needs space). Add mustard seeds and fenugreek seeds (methi)."", ""Add chopped onions, green chilies, and curry leaves. Sauté until onions turn golden brown."", ""Add ginger-garlic paste and sauté for a minute until the raw smell goes away."", ""Add turmeric powder, red chili powder (Andhra style needs more spice), and coriander powder."", ""Pour the extracted tamarind juice and add about 1-2 cups of water depending on how thick you want the gravy."", ""Add salt. Bring the gravy to a rolling boil."", ""Gently drop the raw fish pieces into the boiling gravy one by one."", ""Cover the pan and cook on medium heat for 10-12 minutes."", ""IMPORTANT: Do not stir with a spoon as fish will break. Instead, hold the pan handles and swirl/rotate it gently to mix."", ""Cook until the gravy thickens and oil floats on top."", ""Turn off the heat and garnish with fresh coriander. It tastes better if eaten after a few hours.""]"
Arunachal Pradesh,Thukpa,https://www.google.com/search?tbm=isch&q=Arunachal+Thukpa,30 mins,"Noodles; Vegetables (Carrot/Spinach); Chicken (opt); Ginger-Garlic; Soy Sauce",300 kcal,"[""Heat oil in a large pot over medium heat."", ""Add chopped onions, minced ginger, and minced garlic. Sauté until fragrant and onions are translucent."", ""Add chopped vegetables like carrots, cabbage, and beans (and chicken strips if non-veg). Sauté for 2-3 minutes."", ""Pour in vegetable or chicken stock (or water) and bring it to a rolling boil."", ""Add soy sauce, a little vinegar, salt, and black pepper powder."", ""Add the noodles (egg noodles or plain flour noodles) into the boiling broth."", ""Cook until the noodles are soft but not mushy (usually 5-8 minutes)."", ""Turn off the heat. Garnish generously with chopped spring onions and fresh coriander."", ""Serve piping hot in a bowl.""]"
Arunachal Pradesh,Zan (Millet Porridge),https://www.google.com/search?tbm=isch&q=Arunachal+Pradesh+Zan+Recipe,25 mins,"Millet Flour; Water; Vegetables; Smoked Meat (optional); Spices",250 kcal,"[""Dry roast the millet flour (usually finger millet) in a pan on low heat for 2-3 minutes until it releases a nutty aroma."", ""In a separate pot, bring water to a boil."", ""Slowly add the roasted flour into the boiling water while whisking continuously to ensure no lumps form."", ""Add washed and chopped green leafy vegetables (like spinach or cabbage) and green peas."", ""If using meat, add pre-boiled small meat chunks now."", ""Add salt and butter (or ghee) for flavor."", ""Simmer on low heat, stirring occasionally, until the mixture thickens to a porridge consistency."", ""Serve hot, traditionally eaten with fermented soybeans or chutney.""]"
Arunachal Pradesh,Pika Pila,https://www.google.com/search?tbm=isch&q=Pika+Pila+Recipe,15 mins,"Bamboo Shoots; Pork Fat; King Chili (Bhut Jolokia); Salt",100 kcal,"[""Clean the bamboo shoots properly and slice them into thin strips."", ""In a bowl, combine the sliced bamboo shoots with pork fat (lard)."", ""Add a pinch of baking soda (this softens the bamboo shoots and adds flavor)."", ""Add finely chopped King Chili (Bhut Jolokia) or very spicy red chili flakes."", ""Add salt to taste."", ""Mix everything thoroughly using a spoon or gloved hands (King Chili is very hot)."", ""Let it sit for a few hours for flavors to meld, or serve immediately as a spicy pickle-like side dish.""]"
Arunachal Pradesh,Lukter,https://www.google.com/search?tbm=isch&q=Lukter+Recipe+Arunachal,20 mins,"Cooked Dry Meat; King Chili flakes; Ginger; Garlic",200 kcal,"[""Take cooked dry meat (usually beef or pork that has been smoked and dried) and shred it into fine, thin fibrous strips."", ""Heat a tawa or pan lightly."", ""Dry roast dry red chilies (specifically Bhut Jolokia flakes for authenticity) until crisp."", ""Crush the roasted chilies into flakes."", ""In a bowl, mix the shredded dry meat with the chili flakes."", ""Add crushed ginger and garlic cloves for raw pungency."", ""Add salt and toss everything together until the meat is evenly coated with the spices."", ""Serve as a dry accompaniment to rice and curry.""]"
Arunachal Pradesh,Pehak,https://www.google.com/search?tbm=isch&q=Pehak+Recipe,20 mins,"Fermented Soya Bean; King Chili; Salt; Water",120 kcal,"[""Take the fermented soya bean cake or paste (locally available)."", ""Mash the soya beans thoroughly using a mortar and pestle or back of a spoon."", ""Roast dry red chilies (King Chili) over an open flame until charred and smoky, then crush them."", ""Mix the mashed soya beans with the crushed chilies."", ""Add salt to taste."", ""Add a little warm water to the mixture to bring it to a chutney-like consistency."", ""Mix vigorously to combine all flavors."", ""Serve as a spicy, pungent dip with steamed rice and boiled vegetables.""]"
Assam,Masor Tenga,https://www.google.com/search?tbm=isch&q=Masor+Tenga+Recipe,40 mins,"Rohu Fish; Tomatoes; Lemon or Elephant Apple; Turmeric; Mustard Oil",250 kcal,"[""Clean the fish pieces, rub with turmeric and salt, and leave for 15 minutes."", ""Heat mustard oil in a pan and lightly fry the fish pieces. Remove and keep aside."", ""In the same oil, add fenugreek seeds (methi) and let them splutter."", ""Add chopped tomatoes and turmeric powder. Sauté until tomatoes are pulpy."", ""Add about 2 cups of warm water and salt. Bring to a boil."", ""Gently slide the fried fish pieces into the curry."", ""Squeeze fresh lemon juice (or add elephant apple juice) into the curry for sourness."", ""Simmer for 5-7 minutes. Garnish with coriander and serve with rice.""]"
Assam,Khar,https://www.google.com/search?tbm=isch&q=Assamese+Khar+Recipe,35 mins,"Raw Papaya; Pulses; Kol Khar (Banana Peel Ash filtrate); Mustard Oil",180 kcal,"[""Heat mustard oil in a pan. Add crushed garlic cloves."", ""Add chopped raw papaya and washed pulses (black lentils or split peas). Fry for a few minutes."", ""Add water just enough to cover the ingredients and add salt."", ""Cover and cook until the papaya is soft and pulpy."", ""Add the key ingredient 'Kol Khar' (banana peel ash extract) or a pinch of baking soda."", ""Simmer for another 5 minutes until the gravy thickens slightly."", ""Turn off heat and drizzle 1 tablespoon of raw mustard oil on top before serving.""]"
Assam,Duck Meat Curry,https://www.google.com/search?tbm=isch&q=Assamese+Duck+Meat+Curry,60 mins,"Duck Meat; Ash Gourd (Kumura); Black Pepper; Ginger-Garlic; Whole Spices",450 kcal,"[""Clean and cut the duck meat with skin (skin adds flavor). Marinate with turmeric and salt."", ""Heat oil in a pressure cooker or heavy pot. Add whole spices (bay leaf, cardamom, cinnamon)."", ""Add chopped onions and fry until golden brown."", ""Add ginger-garlic paste and sauté for 2 minutes."", ""Add the duck meat and fry on medium heat for 15-20 minutes until oil separates."", ""Add cumin powder, coriander powder, and red chili powder. Mix well."", ""Add chunks of Ash Gourd (Kumura) and black pepper powder."", ""Add warm water and pressure cook for 4-5 whistles (duck takes longer than chicken).""]"
Assam,Aloo Pitika,https://www.google.com/search?tbm=isch&q=Aloo+Pitika,15 mins,"Potatoes; Mustard Oil; Onions; Green Chilies; Salt; Coriander",150 kcal,"[""Boil potatoes until they are completely soft."", ""Peel the potatoes and mash them thoroughly in a bowl."", ""Add finely chopped raw onions."", ""Add finely chopped green chilies and fresh coriander leaves."", ""Add salt to taste."", ""Pour a generous amount of raw mustard oil (this is crucial for the authentic pungent flavor)."", ""Mix everything together with your hand until well combined."", ""Serve immediately as a side dish with rice and dal.""]"
Assam,Koldil Inkura,https://www.google.com/search?tbm=isch&q=Chicken+with+Banana+Flower+Assam,50 mins,"Chicken; Banana Flower (Koldil); Potatoes; Ginger-Garlic; Spices",300 kcal,"[""Finely chop the Banana Flower (Koldil) and soak in water to prevent browning."", ""Boil the chopped flower with a little salt and turmeric, then drain the water (removes bitterness)."", ""Heat oil in a pan. Add chopped onions and bay leaves."", ""Add chicken or duck meat pieces and sauté until browned."", ""Add ginger-garlic paste, cumin, and coriander powder."", ""Add the boiled banana flower and cubed potatoes."", ""Cover and cook on low heat. Do not add much water; let it cook in its own juices until dry and tender.""]"
Bihar,Litti Chokha,https://www.google.com/search?tbm=isch&q=Litti+Chokha,70 mins,"Wheat Flour; Sattu; Brinjal; Tomato; Garlic; Mustard Oil; Ghee",400 kcal,"[""Dough: Mix wheat flour, ghee, and salt. Knead into a firm dough with water."", ""Filling (Sattu): Mix Sattu (roasted gram flour) with chopped garlic, ginger, green chilies, coriander, onion, mustard oil, pickle masala (achaar), ajwain, and lemon juice."", ""Take a dough ball, flatten it, create a cup shape, stuff the Sattu mixture, and seal it tight into a round ball."", ""Chokha: Roast eggplant (brinjal) and tomatoes over direct flame until skin chars. Peel and mash them. Add chopped onions, chilies, garlic, mustard oil, and salt."", ""Bake the Littis over a coal barbecue (Goitha) or in an oven at 200°C until the crust is brown and hard."", ""Dip the hot Littis in melted Ghee completely."", ""Serve with the Chokha and green chutney.""]"
Bihar,Sattu Paratha,https://www.google.com/search?tbm=isch&q=Sattu+Paratha,30 mins,"Wheat Flour; Sattu (Roasted Gram Flour); Ajwain; Pickle Masala; Onion",280 kcal,"[""Prepare the filling: In a bowl, mix Sattu, finely chopped onion, garlic, ginger, green chilies, kalonji (nigella seeds), ajwain, mustard oil, pickle masala, lemon juice, and salt."", ""Knead a soft dough using whole wheat flour and water."", ""Take a lemon-sized portion of dough, roll it slightly, place the sattu filling in the center, and seal the edges."", ""Roll out the stuffed dough gently into a flat circle (Paratha)."", ""Heat a tawa (griddle). Place the paratha on it."", ""Cook one side, flip, and apply oil or ghee."", ""Flip again and apply oil/ghee on the other side. Cook until golden brown spots appear."", ""Serve hot with curd or pickle.""]"
Bihar,Champaran Meat,https://www.google.com/search?tbm=isch&q=Champaran+Meat,90 mins,"Mutton; Whole Garlic Bulbs; Mustard Oil; Onions; Whole Spices",500 kcal,"[""In a large bowl, take the raw mutton pieces."", ""Add sliced onions, ginger-garlic paste, turmeric, coriander powder, red chili powder, cumin powder, whole spices (garam masala), and salt."", ""Pour raw mustard oil over the meat."", ""Add 2-3 whole garlic bulbs (wash them, do not peel) into the mix."", ""Mix everything thoroughly with your hands."", ""Transfer the mixture into an earthen pot (Handi)."", ""Cover the mouth of the pot with a clay lid and seal the edges with wheat dough."", ""Place the pot on a charcoal fire (or low gas flame) and cook for 60-90 minutes."", ""Shake the pot every 15 minutes to prevent sticking. Do not open until done.""]"
Bihar,Thekua,https://www.google.com/search?tbm=isch&q=Thekua+Recipe,40 mins,"Wheat Flour; Jaggery/Sugar; Ghee; Coconut; Cardamom",350 kcal,"[""In a large bowl, mix whole wheat flour and grated coconut (and fennel seeds if desired)."", ""Add ghee to the flour and rub it with your fingers until it resembles breadcrumbs (Moyen)."", ""Dissolve sugar or jaggery in a little warm water."", ""Add the sweet water to the flour mixture gradually."", ""Knead a very stiff and hard dough (do not make it soft)."", ""Pinch small balls of dough. Press them against a wooden 'Thekua mold' to get a design, or flatten by hand."", ""Heat oil or ghee in a deep pan on low flame."", ""Deep fry the Thekuas on low heat until they turn dark brown and crispy (cooking on high heat will leave them raw inside)."", ""Cool completely to harden before storing.""]"
Bihar,Chana Ghugni,https://www.google.com/search?tbm=isch&q=Bihari+Chana+Ghugni,40 mins,"Black Chickpeas (Kala Chana); Onions; Tomatoes; Ginger-Garlic; Spices",220 kcal,"[""Soak black chickpeas (Kale Chane) overnight. Pressure cook for 3-4 whistles."", ""Heat oil in a pan. Add cumin seeds and bay leaf."", ""Add onion paste (or finely chopped onions) and fry until golden."", ""Add ginger-garlic paste, turmeric, coriander powder, meat masala (optional), and red chili powder."", ""Add chopped tomatoes and salt. Cook until oil separates from the masala."", ""Add the boiled chickpeas along with a little of the boiled water."", ""Cover and cook for 10 minutes so chickpeas absorb the flavor."", ""Garnish with fresh coriander. Serve with puffed rice (Muri) or Chuda.""]"
Chhattisgarh,Chila,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Chila+Recipe,20 mins,"Rice Flour; Urad Dal paste; Water; Green Chilies; Coriander; Salt",150 kcal,"[""Take rice flour in a bowl."", ""Add a small amount of Urad dal paste (optional, for softness) or just use plain rice flour."", ""Add water gradually to make a smooth pouring batter (consistency like Dosa or slightly thinner)."", ""Add salt, finely chopped green chilies, and chopped coriander leaves to the batter."", ""Heat a tawa (griddle) and brush with oil."", ""Pour a ladle full of batter and spread it gently (it is usually thicker than a dosa)."", ""Cover with a lid for 2 minutes to let it steam cook."", ""Remove lid, drizzle oil, flip, and cook the other side until crispy spots appear."", ""Serve hot with tomato chutney.""]"
Chhattisgarh,Fara,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Fara+Recipe,40 mins,"Cooked Rice/Rice Flour; Sesame Seeds; Green Chilies; Mustard Seeds",200 kcal,"[""Make a dough using leftover cooked rice and rice flour (mix and knead well with hot water and salt)."", ""Add sesame seeds and carom seeds (ajwain) to the dough."", ""Take small portions of the dough and roll them between your palms to make finger-like cylindrical shapes."", ""Grease a steamer plate. Arrange the rolls (Fara) on it."", ""Steam for 15-20 minutes until they are firm and cooked."", ""Heat oil in a pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Add the steamed Fara and sauté for 3-4 minutes until slightly crispy on the outside."", ""Serve as a snack.""]"
Chhattisgarh,Dubki Kadhi,https://www.google.com/search?tbm=isch&q=Dubki+Kadhi+Recipe,45 mins,"Curd/Yogurt; Gram Flour (Besan); Urad Dal (for dumplings); Curry Leaves",250 kcal,"[""Soak Urad Dal for 4 hours. Grind it into a thick, fluffy paste with ginger and green chili."", ""In a deep pot, whisk sour curd (yogurt) with gram flour (besan), turmeric, and water to make a thin Kadhi liquid."", ""Bring the Kadhi mixture to a boil on medium heat."", ""Once the Kadhi is boiling, wet your hands, take small portions of the thick Urad dal paste, and drop them directly into the boiling liquid (these dumplings are called 'Dubki')."", ""Do not stir immediately. Let the dumplings cook and firm up in the boiling liquid for 10 minutes."", ""Prepare a tempering (tadka) of mustard seeds, dry red chilies, and curry leaves in oil."", ""Pour the tempering over the Kadhi.""]"
Chhattisgarh,Bafauri,https://www.google.com/search?tbm=isch&q=Bafauri+Recipe,30 mins,"Chana Dal; Onions; Ginger-Garlic; Turmeric; Coriander",180 kcal,"[""Soak Chana Dal (split chickpeas) for 3-4 hours."", ""Drain water and grind it coarsely (do not make a fine paste) with ginger and chilies."", ""Add finely chopped onions, turmeric, chili powder, coriander leaves, and salt to the paste. Mix well."", ""Grease a steamer plate or Idli stand."", ""Make small balls of the mixture and place them in the steamer."", ""Steam for 20-25 minutes until a knife inserted comes out clean."", ""Serve these steamed healthy balls with chutney (can be eaten as is, without frying). ""]"
Chhattisgarh,Muthia,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Muthia,35 mins,"Rice batter; Sesame Seeds; Mustard Seeds; Chilies; Curry Leaves",220 kcal,"[""Take cooked rice (mashed) or rice flour in a bowl."", ""Add besan (gram flour), ginger-chili paste, turmeric, sesame seeds, and fenugreek leaves (methi)."", ""Add salt and a little oil. Knead into a soft dough."", ""Grease your hands and shape the dough into cylindrical rolls."", ""Steam the rolls in a steamer for 20 minutes."", ""Let them cool slightly, then cut them into 1-inch round slices."", ""Heat oil in a pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Add the sliced Muthia pieces and sauté until they turn golden and crispy.""]"
Goa,Goan Fish Curry,https://www.google.com/search?tbm=isch&q=Goan+Fish+Curry,35 mins,"Kingfish/Pomfret; Coconut; Kashmiri Chillies; Tamarind; Turmeric",320 kcal,"[""Clean and wash the fish slices (Kingfish or Pomfret). Rub with salt and turmeric."", ""Grind fresh grated coconut, coriander seeds, cumin, garlic, Kashmiri red chilies, and turmeric into a very fine paste using a little water."", ""Heat a little oil in a pot and sauté sliced onions until soft."", ""Add the ground coconut spice paste to the pot and cook for 2 minutes."", ""Add water to adjust the consistency (not too thin, not too thick) and bring to a boil."", ""Split green chilies and add them."", ""Add tamarind pulp (or kokum) and salt. Let it simmer for a minute."", ""Gently slide the fish slices into the curry."", ""Simmer on low heat for 5-7 minutes. Do not overcook or the fish will break."", ""Turn off heat and serve with steamed rice.""]"
Goa,Chicken Xacuti,https://www.google.com/search?tbm=isch&q=Chicken+Xacuti,55 mins,"Chicken; Roasted Coconut; Poppy Seeds; Dried Red Chilies; Star Anise",400 kcal,"[""Clean chicken pieces and marinate with salt, turmeric, and ginger-garlic paste."", ""Roast grated fresh coconut, dried red chilies, poppy seeds, sesame seeds, coriander seeds, cloves, cinnamon, and star anise in a pan until fragrant and coconut turns golden brown."", ""Cool the roasted ingredients and grind them into a smooth Xacuti paste."", ""Heat oil in a heavy-bottomed pan. Sauté chopped onions until golden."", ""Add the marinated chicken and sear on high heat for 3-4 minutes."", ""Add the ground Xacuti paste and mix well with the chicken."", ""Add water and salt. Cover and cook on medium heat until chicken is tender."", ""Add a pinch of nutmeg powder at the end for aroma."", ""Garnish with coriander and serve with Poi (Goan bread) or rice.""]"
Goa,Pork Vindaloo,https://www.google.com/search?tbm=isch&q=Goan+Pork+Vindaloo,60 mins,"Pork Meat; Vinegar; Garlic; Ginger; Kashmiri Chilies; Cumin",500 kcal,"[""Grind dried Kashmiri red chilies, cumin seeds, peppercorns, cloves, cinnamon, ginger, garlic, and turmeric using Vinegar (do not use water) into a smooth paste."", ""Cut pork (with some fat) into cubes. Rub the ground paste and salt over the meat."", ""Marinate the pork for at least 6-8 hours (or overnight) in the fridge."", ""Heat oil in a pan. Add sliced onions and fry until brown."", ""Add the marinated pork along with the marinade paste."", ""Sear the meat on high heat for 5 minutes."", ""Add a little water (optional, as pork releases fat/juice) and extra vinegar if needed."", ""Cover and cook on low heat for 45-60 minutes until the meat is fork-tender."", ""The dish should have a layer of oil/fat floating on top. Serve with rice or bread.""]"
Goa,Bebinca,https://www.google.com/search?tbm=isch&q=Goan+Bebinca,4 hours,"All-Purpose Flour; Coconut Milk; Egg Yolks; Sugar; Ghee; Nutmeg",350 kcal,"[""Extract thick coconut milk from grated coconut."", ""In a bowl, mix sugar and egg yolks until creamy."", ""Add the coconut milk and flour to the yolk mixture. Mix until smooth batter forms. Add nutmeg powder."", ""Preheat the oven (or use a grill). Grease a baking tin with ghee."", ""Pour a thin layer (approx 1/2 cup) of batter into the tin. Bake/Grill until the top is golden brown."", ""Remove from oven, brush melted ghee on the baked layer."", ""Pour another thin layer of batter on top of the first baked layer."", ""Bake again until golden. Repeat this process for 7 to 16 layers."", ""Cool completely before unmolding. Slice and serve.""]"
Goa,Sorpotel,https://www.google.com/search?tbm=isch&q=Goan+Sorpotel,60 mins,"Pork Meat & Liver; Vinegar; Dried Chilies; Spices; Ginger-Garlic",450 kcal,"[""Boil the large pieces of pork meat and liver with little water and salt for 20 minutes. Drain and keep the stock."", ""Cut the parboiled meat and liver into tiny, small cubes."", ""Heat oil in a pan and shallow fry the meat cubes until light brown. Remove and keep aside."", ""In the same oil, fry the Sorpotel masala paste (made by grinding red chilies, garlic, ginger, cloves, cinnamon, cumin, and vinegar)."", ""Add the fried meat cubes to the masala."", ""Add the reserved stock water and more vinegar (Sorpotel is tangy)."", ""Simmer on low heat for 30-40 minutes until the gravy thickens."", ""It tastes best if matured for 2-3 days before serving.""]"
Gujarat,Khaman Dhokla,https://www.google.com/search?tbm=isch&q=Khaman+Dhokla,25 mins,"Gram Flour (Besan); Yogurt; Eno/Soda; Mustard Seeds; Green Chilies",160 kcal,"[""In a bowl, mix besan (gram flour), semolina (suji), lemon juice, ginger-green chili paste, sugar, and salt."", ""Add water gradually to make a smooth, lump-free batter (pouring consistency)."", ""Let the batter rest for 15 minutes."", ""Just before steaming, add Fruit Salt (Eno) or baking soda to the batter and whisk briskly for 10 seconds (batter will froth up)."", ""Immediately pour into a greased thali/plate."", ""Steam in a steamer/cooker for 15-20 minutes on high flame."", ""Insert a knife to check; if it comes out clean, it's done. Let it cool slightly."", ""Tempering: Heat oil, add mustard seeds, sesame seeds, curry leaves, and green chilies. Add 1/2 cup water and sugar to the oil and boil."", ""Cut Dhokla into squares and pour the tempering water over it (this makes it juicy)."", ""Garnish with coriander and fresh coconut.""]"
Gujarat,Undhiyu,https://www.google.com/search?tbm=isch&q=Undhiyu+Recipe,60 mins,"Mixed Winter Vegetables (Papdi; Potato; Yam); Muthiya (Fenugreek balls); Spices",400 kcal,"[""Prepare Muthiya: Mix besan, fenugreek leaves, spices, and oil. Shape into small ovals and fry them."", ""Make a green masala paste: Grind coconut, coriander, green chilies, ginger, garlic, and sugar."", ""Slit small brinjals and potatoes (without cutting fully). Stuff them with the green masala."", ""Heat plenty of oil in a heavy pot. Add carom seeds (ajwain)."", ""Layer the vegetables: Add beans (surti papdi), yam (kand), and raw banana first."", ""Add the stuffed potatoes and brinjals on top."", ""Sprinkle the remaining green masala, salt, and a little water."", ""Cover tightly and slow cook for 30 minutes."", ""Add the fried Muthiya on top in the last 10 minutes of cooking (so they don't break)."", ""Garnish with coriander and serve with Puri.""]"
Gujarat,Thepla,https://www.google.com/search?tbm=isch&q=Methi+Thepla,20 mins,"Wheat Flour; Fenugreek Leaves (Methi); Yogurt; Sesame Seeds; Spices",220 kcal,"[""In a large bowl, take whole wheat flour."", ""Add finely chopped fresh fenugreek leaves (methi)."", ""Add yogurt (curd), sesame seeds, turmeric, red chili powder, coriander powder, sugar, and salt."", ""Add a tablespoon of oil."", ""Knead into a soft dough. Use a little water only if needed (methi releases water)."", ""Pinch small balls and roll them into thin circles (thinner than roti) using dry flour."", ""Heat a tawa. Place the Thepla on it."", ""Flip when bubbles appear. Apply oil on both sides."", ""Press with a spatula and cook until brown spots appear."", ""Serve with pickle and curd.""]"
Gujarat,Khandvi,https://www.google.com/search?tbm=isch&q=Gujarati+Khandvi,40 mins,"Gram Flour; Yogurt; Turmeric; Mustard Seeds; Coconut",180 kcal,"[""In a bowl, whisk besan (gram flour) and sour buttermilk (or yogurt + water) until completely smooth with no lumps."", ""Add turmeric and salt."", ""Pour mixture into a non-stick pan. Cook on low heat, stirring CONSTANTLY."", ""The mixture will thicken into a paste. Cook until it leaves the sides of the pan (takes 8-10 mins)."", ""Quickly spread the hot paste thinly on the back of greased plates or a clean countertop using a spatula."", ""Let it cool for 5 minutes."", ""Cut into strips and roll them up tightly."", ""Tempering: Heat oil, add mustard seeds, sesame seeds, green chilies, and curry leaves."", ""Pour tempering over the rolls. Garnish with coriander and grated coconut.""]"
Gujarat,Handvo,https://www.google.com/search?tbm=isch&q=Gujarati+Handvo,50 mins,"Rice & Lentil Batter; Bottle Gourd; Spices; Sesame Seeds",250 kcal,"[""Wash and soak rice and mixed dals (toor, chana, urad) for 4-5 hours."", ""Grind to a coarse batter (like idli batter). Ferment overnight (or 8 hours)."", ""Add grated bottle gourd (lauki), ginger-chili paste, turmeric, sugar, salt, and a little oil to the fermented batter."", ""Add a pinch of baking soda just before cooking."", ""Heat oil in a heavy pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Pour a thick layer of batter into the pan."", ""Cover and cook on very low heat for 10-15 minutes until the bottom is crisp and golden."", ""Carefully flip and cook the other side."", ""Serve slices with chutney.""]"
Haryana,Bajra Khichdi,https://www.google.com/search?tbm=isch&q=Bajra+Khichdi+Haryana,50 mins,"Bajra (Pearl Millet); Moong Dal; Ghee; Salt; Water",350 kcal,"[""Wash Bajra (Pearl Millet) and Moong Dal separately. Soak bajra for 4-6 hours (helps cooking)."", ""In a pressure cooker, add the soaked bajra, dal, and 4 cups of water."", ""Add salt."", ""Pressure cook for 4-5 whistles on medium heat. Then simmer on low for 10 minutes."", ""Open the cooker once pressure releases. Mash the mixture with a ladle or wooden masher until creamy."", ""If it's too thick, add boiling water and simmer."", ""Serve piping hot with a big dollop of Desi Ghee (crucial for taste) and curd.""]"
Haryana,Haryanvi Churma,https://www.google.com/search?tbm=isch&q=Haryanvi+Roti+Churma,30 mins,"Wheat Flour; Ghee; Bura (Powdered Sugar) or Jaggery",500 kcal,"[""Knead whole wheat flour with water to make a step-by-step instructions stiff dough."", ""Roll out thick rotis (bread)."", ""Cook the rotis on a tawa (or clay oven) until fully cooked and slightly crisp."", ""While the rotis are still very hot, break them into pieces in a large bowl."", ""Add a generous amount of melted Ghee and Bura (powdered sugar) or crushed Jaggery."", ""Crush everything together using your hands (this is the traditional way) until it turns into a coarse crumble."", ""Make ladoos or serve as loose crumble. Eat warm.""]"
Haryana,Kadhi Pakora,https://www.google.com/search?tbm=isch&q=Haryanvi+Kadhi+Pakora,45 mins,"Sour Curd (Lassi); Besan (Gram Flour); Spices; Methi Seeds; Oil",300 kcal,"[""Pakora: Mix besan, chopped onion, spices, and water to make thick batter. Deep fry small fritters (pakoras) in oil."", ""Kadhi Base: In a bowl, whisk sour yogurt and besan with water to make a lump-free thin liquid."", ""Heat oil in a deep pot. Add fenugreek seeds (methi), cumin, and dried red chilies."", ""Pour the yogurt-besan mixture into the pot. Stir continuously until it boils (to prevent curdling)."", ""Add turmeric, salt, and red chili powder."", ""Simmer on low heat for at least 30-40 minutes (the longer it cooks, the better)."", ""Add the fried pakoras to the boiling Kadhi and cook for another 5 minutes."", ""Finish with a second tempering of ghee and red chili powder on top.""]"
Haryana,Bajre Ki Roti & Lasun Chatni,https://www.google.com/search?tbm=isch&q=Bajre+Ki+Roti+Lasun+Chutney,35 mins,"Bajra Flour; Garlic; Dry Red Chilies; Salt; Butter (White Makhan)",350 kcal,"[""Roti: Take Bajra flour, add a pinch of salt. Add hot water gradually."", ""Knead firmly with the palm of your hand until the dough is soft and pliable."", ""Take a portion, dust with dry flour, and pat it between your palms to flatten it (traditional method) or roll gently."", ""Place on a hot tawa. Cook one side, flip, and apply water lightly on top (prevents cracking)."", ""Roast on open flame until puffed and brown spots appear."", ""Chatni: In a mortar and pestle, crush garlic cloves, dry red chilies, and salt together into a coarse paste."", ""Add a little curd or water to adjust consistency."", ""Serve the hot Roti with a big spoon of white butter (Makhan) and the garlic chutney.""]"
Haryana,Bathua Raita,https://www.google.com/search?tbm=isch&q=Bathua+Raita+Recipe,20 mins,"Bathua Leaves (Chenopodium); Curd/Yogurt; Roasted Cumin; Black Salt",120 kcal,"[""Pick the leaves of Bathua (Chenopodium) and wash thoroughly (it holds soil)."", ""Boil the leaves in a little water for 5-7 minutes until soft."", ""Drain and grind the leaves into a smooth paste."", ""In a bowl, whisk fresh curd (dahi) until smooth."", ""Add the Bathua paste to the curd."", ""Add roasted cumin powder, black salt, and red chili powder. Mix well."", ""(Optional) You can add a tempering of cumin seeds in ghee."", ""Serve chilled as a side dish.""]"
Himachal Pradesh,Chana Madra (Dham),https://www.google.com/search?tbm=isch&q=Himachali+Chana+Madra,50 mins,"Chickpeas (Kabuli Chana); Yogurt; Ghee; Cloves; Cardamom; Turmeric",400 kcal,"1. Boil chickpeas until soft. 2. Heat ghee and cook whole spices. 3. Add beaten yogurt and stir continuously to prevent curdling. 4. Add chickpeas and simmer until gravy thickens."
Himachal Pradesh,Siddu,https://www.google.com/search?tbm=isch&q=Himachali+Siddu+Recipe,90 mins,"Wheat Flour; Yeast; Poppy Seeds/Walnuts (filling); Ghee",350 kcal,"1. Knead dough with yeast and let it rise. 2. Make a filling of poppy seeds or walnuts. 3. Stuff dough balls and shape like a calzone. 4. Steam for 20 mins. Serve hot with melted Ghee."
Himachal Pradesh,Babru,https://www.google.com/search?tbm=isch&q=Himachali+Babru,40 mins,"Whole Wheat Flour; Black Gram Dal (Urad); Oil; Spices",300 kcal,"1. Soak black gram dal overnight and grind to paste. 2. Season the paste. 3. Stuff the paste into wheat dough balls. 4. Roll out and deep fry like a Puri. Served with tamarind chutney."
Himachal Pradesh,Tudkiya Bhath,https://www.google.com/search?tbm=isch&q=Tudkiya+Bhath,50 mins,"Rice; Lentils (Masoor); Potatoes; Yogurt; Tomatoes; Cinnamon; Cardamom",320 kcal,"1. Soak rice and lentils. 2. Sauté spices; onions; tomatoes; and potatoes in ghee. 3. Add yogurt and mix. 4. Add rice/lentils and water. Cook until done like a spicy Pulao."
Himachal Pradesh,Chha Gosht,https://www.google.com/search?tbm=isch&q=Chha+Gosht+Himachal,70 mins,"Lamb/Mutton; Buttermilk; Gram Flour (Besan); Ginger-Garlic; Coriander",450 kcal,"1. Marinate lamb pieces. 2. Fry lamb with spices. 3. Whisk buttermilk with a little gram flour. 4. Add to lamb and slow cook until the meat falls off the bone and gravy is rich."
Jharkhand,Dhuska,https://www.google.com/search?tbm=isch&q=Dhuska+Jharkhand,40 mins,"Rice; Chana Dal; Urad Dal; Green Chilies; Cumin",250 kcal,"1. Soak rice/dals and grind to batter. 2. Add spices. 3. Deep fry ladlefuls in hot oil until golden puffs form."
Jharkhand,Rugra (Mushroom Curry),https://www.google.com/search?tbm=isch&q=Rugra+Recipe,35 mins,"Rugra (Local Mushroom); Onions; Tomatoes; Garlic; Spices",180 kcal,"1. Wash Rugra thoroughly. 2. Sauté onion-tomato masala. 3. Add Rugra and cook until tender. Tastes like meat."
Jharkhand,Chilka Roti,https://www.google.com/search?tbm=isch&q=Chilka+Roti,25 mins,"Rice Flour; Chana Dal; Water; Salt",200 kcal,"1. Grind soaked rice and dal to a batter. 2. Pour on a tawa like a crepe. 3. Cook covered. Served with mutton or chana."
Jharkhand,Bamboo Shoot Curry,https://www.google.com/search?tbm=isch&q=Bamboo+Shoot+Curry+Jharkhand,30 mins,"Fermented Bamboo Shoots; Mustard Oil; Garlic; Red Chilies",150 kcal,"1. Fry crushed garlic and chilies. 2. Add bamboo shoots and salt. 3. Cook until moisture evaporates."
Jharkhand,Arsa Roti,https://www.google.com/search?tbm=isch&q=Arsa+Roti,40 mins,"Rice Flour; Jaggery Syrup; Sesame Seeds; Oil",350 kcal,"1. Mix rice flour with hot jaggery syrup to make dough. 2. Flatten into discs. 3. Deep fry until dark brown."
Karnataka,Bisi Bele Bath,https://www.google.com/search?tbm=isch&q=Bisi+Bele+Bath,50 mins,"Rice; Toor Dal; Tamarind; Jaggery; Vegetables; Spice Powder",350 kcal,"1. Cook rice and dal. 2. Cook veggies separately. 3. Mix all with tamarind and special masala. 4. Simmer and temper with cashews."
Karnataka,Mysore Masala Dosa,https://www.google.com/search?tbm=isch&q=Mysore+Masala+Dosa,40 mins,"Rice-Urad Batter; Red Chutney (Garlic-Chili); Potato Bhaji; Butter",320 kcal,"1. Spread dosa batter. 2. Smear red chutney inside. 3. Place potato filling. 4. Fold with a dollop of butter."
Karnataka,Ragi Mudde,https://www.google.com/search?tbm=isch&q=Ragi+Mudde,25 mins,"Ragi (Finger Millet) Flour; Water; Ghee",180 kcal,"1. Boil water; add flour and stir vigorously to remove lumps. 2. Steam. 3. Shape into balls with wet hands. Swallow, don't chew."
Karnataka,Neer Dosa,https://www.google.com/search?tbm=isch&q=Neer+Dosa,20 mins,"Rice; Coconut; Salt; Water",140 kcal,"1. Grind soaked rice and coconut to watery batter. 2. Pour on tawa (don't spread). 3. Cover and cook (no fermentation needed)."
Karnataka,Mysore Pak,https://www.google.com/search?tbm=isch&q=Mysore+Pak,40 mins,"Gram Flour (Besan); Sugar; Ghee (Lots of it)",500 kcal,"1. Roast besan in ghee. 2. Make sugar syrup. 3. Add besan and pour hot ghee continuously until porous texture forms."
Kerala,Appam with Stew,https://www.google.com/search?tbm=isch&q=Appam+Stew,45 mins,"Rice Flour; Coconut Milk; Yeast; Veggies/Chicken",280 kcal,"1. Ferment batter. 2. Make Appams in curved pan. 3. Cook stew with coconut milk and mild spices."
Kerala,Puttu and Kadala Curry,https://www.google.com/search?tbm=isch&q=Puttu+Kadala,40 mins,"Rice Flour; Coconut; Black Chickpeas; Spices",300 kcal,"1. Steam rice flour and coconut layers in Puttu maker. 2. Cook spicy black chickpea curry to serve with it."
Kerala,Karimeen Pollichathu,https://www.google.com/search?tbm=isch&q=Karimeen+Pollichathu,50 mins,"Pearl Spot Fish; Banana Leaves; Onion; Tomato; Spices",350 kcal,"1. Marinate fish. 2. Make thick masala paste. 3. Wrap fish and masala in banana leaf. 4. Pan fry/roast the packet."
Kerala,Malabar Parotta,https://www.google.com/search?tbm=isch&q=Malabar+Parotta,60 mins,"Maida (Refined Flour); Egg; Oil/Ghee; Water",400 kcal,"1. Knead soft dough. 2. Create pleats/layers by flipping and folding. 3. Coil and roll out. 4. Fry with oil until flaky."
Kerala,Avial,https://www.google.com/search?tbm=isch&q=Kerala+Avial,30 mins,"Mixed Vegetables (Yam; Drumstick; Carrot; etc.); Coconut; Curd; Coconut Oil",200 kcal,"1. Boil vegetables with turmeric. 2. Grind coconut and cumin. 3. Mix vegetables; coconut paste and curd. 4. Finish with raw coconut oil."
Madhya Pradesh,Poha,https://www.google.com/search?tbm=isch&q=Indori+Poha,15 mins,"Flattened Rice; Fennel Seeds; Onions; Sev; Pomegranate",200 kcal,"1. Rinse Poha. 2. Temper with mustard and fennel seeds. 3. Steam. 4. Top with Jeeravan masala; Sev; and onions."
Madhya Pradesh,Dal Bafla,https://www.google.com/search?tbm=isch&q=Dal+Bafla,60 mins,"Wheat Flour; Maize Flour; Ghee; Mixed Dal",450 kcal,"1. Make dough balls. 2. Boil them in water first; then bake/roast. 3. Crush and dip in Ghee. Serve with Dal."
Madhya Pradesh,Bhutte Ka Kees,https://www.google.com/search?tbm=isch&q=Bhutte+Ka+Kees,30 mins,"Grated Corn; Milk; Mustard Seeds; Coconut; Spices",250 kcal,"1. Grate fresh corn. 2. Sauté spices; add corn and milk. 3. Cook until thick and creamy. 4. Garnish with coriander/coconut."
Madhya Pradesh,Bhopali Gosht Korma,https://www.google.com/search?tbm=isch&q=Bhopali+Gosht+Korma,60 mins,"Mutton; Yogurt; Spices; Coriander Seeds; Onions",400 kcal,"1. Make a rich gravy with browned onions and yogurt. 2. Slow cook mutton with whole spices until very tender."
Madhya Pradesh,Mawa Bati,https://www.google.com/search?tbm=isch&q=Mawa+Bati,45 mins,"Mawa (Khoya); Arrowroot powder; Dry Fruits; Sugar Syrup",400 kcal,"1. Make dough with Mawa and arrowroot. 2. Stuff with dry fruits. 3. Deep fry balls. 4. Soak in sugar syrup (like Gulab Jamun)."
Maharashtra,Vada Pav,https://www.google.com/search?tbm=isch&q=Vada+Pav,40 mins,"Potatoes; Gram Flour; Pav Bun; Garlic Chutney",300 kcal,"1. Fry spiced potato balls in batter. 2. Slit Pav bun. 3. Apply spicy garlic powder and place Vada inside."
Maharashtra,Misal Pav,https://www.google.com/search?tbm=isch&q=Misal+Pav,45 mins,"Sprouted Moth Beans; Farsan (Crunchy mix); Onions; Pav",450 kcal,"1. Cook spicy curry with sprouts (Misal). 2. Top with Farsan and onions. 3. Serve with Pav and lemon."
Maharashtra,Puran Poli,https://www.google.com/search?tbm=isch&q=Puran+Poli,60 mins,"Chana Dal; Jaggery; Wheat Flour; Cardamom; Ghee",350 kcal,"1. Cook dal and jaggery paste (Puran). 2. Stuff inside wheat dough. 3. Roll thin and cook on tawa with Ghee."
Maharashtra,Pav Bhaji,https://www.google.com/search?tbm=isch&q=Pav+Bhaji,40 mins,"Mixed Vegetables; Butter; Pav Bhaji Masala; Pav",400 kcal,"1. Boil and mash vegetables. 2. Cook with butter and masala on a large tawa. 3. Serve with buttered toasted Pav."
Maharashtra,Modak,https://www.google.com/search?tbm=isch&q=Ukadiche+Modak,50 mins,"Rice Flour; Coconut; Jaggery; Cardamom",250 kcal,"1. Make rice flour dough. 2. Make sweet coconut-jaggery filling. 3. Pleat dough around filling and steam."
Manipur,Kangshoi,https://www.google.com/search?tbm=isch&q=Kangshoi,25 mins,"Seasonal Veggies; Dry Fish; Water; Onion",100 kcal,"1. Boil water with dry fish/fried fish. 2. Add veggies. 3. Stew without oil. Healthy and soupy."
Manipur,Eromba,https://www.google.com/search?tbm=isch&q=Eromba,20 mins,"Boiled Vegetables; Fermented Fish (Ngari); King Chili",150 kcal,"1. Mash boiled veggies. 2. Mix with steamed fermented fish and spicy chilies. 3. Garnish with herbs."
Manipur,Chak-Hao Kheer,https://www.google.com/search?tbm=isch&q=Chak+Hao+Kheer,50 mins,"Black Rice; Milk; Sugar; Cardamom; Dry Fruits",300 kcal,"1. Soak purple/black rice. 2. Slow cook in milk until it turns purple and creamy. 3. Add sugar and nuts."
Manipur,Singju,https://www.google.com/search?tbm=isch&q=Singju+Salad,20 mins,"Lotus Root; Cabbage; Herbs; Perilla Seeds; Chili",120 kcal,"1. Finely chop raw vegetables. 2. Roast and grind perilla seeds/chickpea flour. 3. Toss everything together as a spicy salad."
Manipur,Nga Thongba,https://www.google.com/search?tbm=isch&q=Nga+Thongba,40 mins,"Fish; Potatoes; Turmeric; Herbs (Ooti)",250 kcal,"1. Fry fish slightly. 2. Cook curry with potatoes and local herbs. 3. Simmer until fish is soft."
Meghalaya,Jadoh,https://www.google.com/search?tbm=isch&q=Jadoh,45 mins,"Red Rice; Pork/Chicken; Onions; Ginger; Black Pepper",400 kcal,"1. Sauté meat cubes. 2. Add rice and turmeric. 3. Cook with water until rice is fluffy and meat is tender."
Meghalaya,Doh Khleh,https://www.google.com/search?tbm=isch&q=Doh+Khleh,30 mins,"Pork; Onions; Ginger; Chillies; Salt",300 kcal,"1. Boil pork until soft. 2. Mince or chop finely. 3. Mix with raw onions; ginger; and chilies (like a salad)."
Meghalaya,Nakham Bitchi,https://www.google.com/search?tbm=isch&q=Nakham+Bitchi,20 mins,"Dry Fish; Vegetables; Soda; Chilies",100 kcal,"1. Fry dry fish. 2. Boil water with vegetables. 3. Add fish and soda. Served as a soup."
Meghalaya,Pumaloi,https://www.google.com/search?tbm=isch&q=Pumaloi,40 mins,"Powdered Rice; Water; Coconut (optional)",200 kcal,"1. Steam powdered rice in a special pot (Khiew Ranei). 2. Serve hot with curry."
Meghalaya,Tungrymbai,https://www.google.com/search?tbm=isch&q=Tungrymbai,45 mins,"Fermented Soybeans; Pork fat; Sesame seeds; Ginger",350 kcal,"1. Mash fermented beans. 2. Cook with pork fat and sesame paste slowly until flavor blends."
Mizoram,Sanpiau,https://www.google.com/search?tbm=isch&q=Sanpiau,30 mins,"Rice Porridge; Fish Sauce; Coriander; Spring Onions",250 kcal,"1. Cook rice into porridge. 2. Top with fresh herbs; fish sauce; and crushed black pepper."
Mizoram,Vawksa Rep,https://www.google.com/search?tbm=isch&q=Vawksa+Rep,40 mins,"Smoked Pork; Chilies; Local Herbs; Leafy Greens",350 kcal,"1. Stir fry smoked pork with greens and chilies. 2. Add little water to cook through."
Mizoram,Bai,https://www.google.com/search?tbm=isch&q=Mizo+Bai,25 mins,"Vegetables; Pork Sauce (Sa-um); Spinach; Bamboo Shoot",150 kcal,"1. Boil water with fermented pork sauce. 2. Add vegetables and shoots. 3. Cook until soft (Stew)."
Mizoram,Koat Pitha,https://www.google.com/search?tbm=isch&q=Koat+Pitha,30 mins,"Rice Flour; Banana; Jaggery; Oil",250 kcal,"1. Mash bananas with flour and jaggery. 2. Deep fry batter fritters. 3. Serve as a sweet snack."
Mizoram,Panch Phoron Tarka,https://www.google.com/search?tbm=isch&q=Panch+Phoron+Tarka+Mizoram,30 mins,"Pumpkin; Potatoes; Panch Phoron Spice; Dry Chili",200 kcal,"1. Cut veggies. 2. Temper oil with Panch Phoron. 3. Stir fry veggies until cooked."
Nagaland,Smoked Pork with Bamboo Shoot,https://www.google.com/search?tbm=isch&q=Smoked+Pork+Bamboo+Shoot,60 mins,"Smoked Pork; Fermented Bamboo Shoot; Raja Mircha",450 kcal,"1. Wash pork. 2. Cook with ginger and chili. 3. Add bamboo shoots. 4. Simmer until gravy is thick."
Nagaland,Axone (Akhuni),https://www.google.com/search?tbm=isch&q=Axone+Curry,45 mins,"Fermented Soybeans (Axone); Smoked Pork/Beef; Chilies; Ginger",400 kcal,"1. Crush Axone cakes. 2. Add to pot with meat; ginger and chilies. 3. Stew until pungent and cooked."
Nagaland,Galho,https://www.google.com/search?tbm=isch&q=Galho+Nagaland,35 mins,"Rice; Vegetables; Smoked Meat; Axone (optional)",300 kcal,"1. Mix rice; veggies; and meat. 2. Boil together like a Khichdi/Risotto. 3. Serve warm."
Nagaland,Hinkejvu,https://www.google.com/search?tbm=isch&q=Hinkejvu,25 mins,"Colocasia; Cabbage; Mustard Leaves; French Beans",120 kcal,"1. Boil assorted vegetables together. 2. Add salt and local herbs. 3. Cook until water dries up."
Nagaland,Rosep Aon,https://www.google.com/search?tbm=isch&q=Rosep+Aon,30 mins,"Mixed Vegetables; Dry Fish; Sichuan Pepper",150 kcal,"1. Boil vegetables and dry fish. 2. Mash lightly. 3. Season with Sichuan pepper and herbs."
Odisha,Dalma,https://www.google.com/search?tbm=isch&q=Dalma+Recipe,45 mins,"Toor Dal; Pumpkin; Raw Banana; Brinjal; Panch Phoron",220 kcal,"1. Boil dal with veggies. 2. Temper with panch phoron (5 spice mix) and coconut."
Odisha,Chhena Poda,https://www.google.com/search?tbm=isch&q=Chhena+Poda,90 mins,"Fresh Chhena (Cottage Cheese); Sugar; Cardamom; Sal Leaves",300 kcal,"1. Knead Chhena with sugar. 2. Bake in a tin lined with sal leaves/parchment until crust is dark brown."
Odisha,Pakhala Bhata,https://www.google.com/search?tbm=isch&q=Pakhala+Bhata,10 mins,"Cooked Rice; Water; Curd; Green Chili; Mustard Seeds",150 kcal,"1. Soak cooked rice in water (ferment overnight for best taste). 2. Add curd; salt; and tempered spices."
Odisha,Macha Ghanta,https://www.google.com/search?tbm=isch&q=Macha+Ghanta,60 mins,"Fish Head; Chana Dal; Potatoes; Onions; Spices",350 kcal,"1. Fry fish head. 2. Cook dal and veggies. 3. Mix everything with spicy gravy."
Odisha,Chungdi Malai,https://www.google.com/search?tbm=isch&q=Chungdi+Malai,40 mins,"Prawns; Coconut Milk; Ginger-Garlic; Spices",320 kcal,"1. Sauté marinated prawns. 2. Add onion masala. 3. Add coconut milk and simmer."
Punjab,Butter Chicken,https://www.google.com/search?tbm=isch&q=Butter+Chicken,50 mins,"Chicken; Tomatoes; Butter; Cream; Cashews; Fenugreek",450 kcal,"1. Tandoor roast the chicken. 2. Make tomato-butter-cream gravy. 3. Simmer chicken in gravy. 4. Garnish with kasuri methi."
Punjab,Sarson Da Saag & Makki Roti,https://www.google.com/search?tbm=isch&q=Sarson+Da+Saag,90 mins,"Mustard Greens; Spinach; Maize Flour; Ghee",400 kcal,"1. Slow cook and mash greens. 2. Temper with garlic/ginger. 3. Serve with Maize flour flatbread and white butter."
Punjab,Chole Bhature,https://www.google.com/search?tbm=isch&q=Chole+Bhature,60 mins,"Chickpeas; Maida; Spices; Tea bags (for color)",550 kcal,"1. Pressure cook chickpeas with spices. 2. Make fermented dough for Bhature. 3. Deep fry Bhature and serve with spicy Chole."
Punjab,Amritsari Kulcha,https://www.google.com/search?tbm=isch&q=Amritsari+Kulcha,45 mins,"Refined Flour; Potato filling; Coriander Seeds; Butter",350 kcal,"1. Stuff dough with spicy potato mix. 2. Bake in Tandoor/Oven until carpet. 3. Crush with hands and add butter."
Punjab,Dal Makhani,https://www.google.com/search?tbm=isch&q=Dal+Makhani,8 hours,"Whole Black Urad; Kidney Beans; Butter; Cream",400 kcal,"1. Slow cook lentils overnight or for hours. 2. Add tomato puree and spices. 3. Finish with heavy cream and butter."
Rajasthan,Dal Baati Churma,https://www.google.com/search?tbm=isch&q=Dal+Baati+Churma,90 mins,"Wheat Flour; Mixed Lentils; Ghee; Semolina",600 kcal,"1. Bake hard wheat balls (Baati). 2. Cook spicy Panchmel Dal. 3. Grind Baati with sugar/ghee for Churma."
Rajasthan,Laal Maas,https://www.google.com/search?tbm=isch&q=Laal+Maas,60 mins,"Mutton; Mathania Red Chilies; Yogurt; Garlic",450 kcal,"1. Make paste of soaked red chilies. 2. Cook mutton with chili paste and yogurt. 3. Simmer until meat is tender and red."
Rajasthan,Gatte Ki Sabzi,https://www.google.com/search?tbm=isch&q=Gatte+Ki+Sabzi,40 mins,"Gram Flour (Besan); Curd; Spices",300 kcal,"1. Make dough of besan and boil rolls. 2. Cut into discs (Gatte). 3. Cook in spicy yogurt gravy."
Rajasthan,Ker Sangri,https://www.google.com/search?tbm=isch&q=Ker+Sangri,30 mins,"Dried Ker Berries; Sangri Beans; Spices; Oil",250 kcal,"1. Soak dried berries/beans. 2. Cook with lots of oil and spices. 3. Can be stored for days."
Rajasthan,Ghevar,https://www.google.com/search?tbm=isch&q=Ghevar,60 mins,"Flour; Ghee; Ice cubes; Sugar Syrup; Rabdi",450 kcal,"1. Make batter using ghee and ice. 2. Deep fry in ring mold to get honeycomb texture. 3. Dip in sugar syrup. Top with Rabdi."
Sikkim,Momo,https://www.google.com/search?tbm=isch&q=Sikkim+Momo,40 mins,"Flour; Minced Meat/Vegetable; Onion; Garlic",200 kcal,"1. Prepare dough. 2. Fill with mixture. 3. Steam. 4. Serve with spicy chili sauce."
Sikkim,Thukpa,https://www.google.com/search?tbm=isch&q=Sikkim+Thukpa,30 mins,"Noodle; Vegetable/Meat Broth; Garlic; Soy Sauce",300 kcal,"1. Prepare spicy broth. 2. Add veggies/meat. 3. Add noodles. 4. Serve hot soup."
Sikkim,Phagshapa,https://www.google.com/search?tbm=isch&q=Phagshapa,45 mins,"Pork Fat strips; Radish; Dried Chilies",400 kcal,"1. Stew pork strips with radish. 2. Add dried chilies. 3. Cook until tender and slightly tangy."
Sikkim,Sha Phaley,https://www.google.com/search?tbm=isch&q=Sha+Phaley,40 mins,"Dough; Minced Beef/Chicken; Cabbage; Onion",350 kcal,"1. Roll dough into circles. 2. Stuff with spiced meat. 3. Seal semi-circle. 4. Deep fry until golden."
Sikkim,Gundruk,https://www.google.com/search?tbm=isch&q=Gundruk+Soup,20 mins,"Fermented Leafy Greens; Tomato; Garlic",100 kcal,"1. Soak fermented leaves. 2. Cook soup with tomatoes and spices. tangy taste."
Tamil Nadu,Idli Sambar,https://www.google.com/search?tbm=isch&q=Idli+Sambar,40 mins,"Rice-Urad Batter; Toor Dal; Veggies; Tamarind",200 kcal,"1. Steam fermented batter. 2. Cook dal with veggies and sambar powder. 3. Serve together."
Tamil Nadu,Chettinad Chicken,https://www.google.com/search?tbm=isch&q=Chettinad+Chicken,50 mins,"Chicken; Roasted Spices (Pepper; Fennel); Coconut; Curry Leaves",350 kcal,"1. Roast and grind whole spices. 2. Marinate chicken. 3. Cook in spicy masala until gravy is thick."
Tamil Nadu,Pongal,https://www.google.com/search?tbm=isch&q=Ven+Pongal,30 mins,"Rice; Moong Dal; Black Pepper; Cumin; Ghee; Cashews",300 kcal,"1. Cook rice and moong dal together until mushy. 2. Temper generously with ghee; pepper; cumin and cashews."
Tamil Nadu,Chicken 65,https://www.google.com/search?tbm=isch&q=Chicken+65,30 mins,"Chicken cubes; Cornflour; Curd; Red Chili; Curry Leaves",350 kcal,"1. Marinate chicken in spicy batter. 2. Deep fry. 3. Toss with curry leaves and green chilies."
Tamil Nadu,Paniyaram,https://www.google.com/search?tbm=isch&q=Kuzhi+Paniyaram,20 mins,"Leftover Idli Batter; Onions; Green Chili; Mustard Seeds",180 kcal,"1. Season batter with sautéed onions. 2. Pour into Paniyaram pan moulds. 3. Cook until golden balls form."
Telangana,Hyderabadi Haleem,https://www.google.com/search?tbm=isch&q=Hyderabadi+Haleem,4 hours,"Mutton; Broken Wheat; Lentils; Ghee; Spices",500 kcal,"1. Slow cook meat and wheat for hours. 2. Mash continuously until pasty and elastic. 3. Top with fried onions and ghee."
Telangana,Sarva Pindi,https://www.google.com/search?tbm=isch&q=Sarva+Pindi,30 mins,"Rice Flour; Chana Dal; Peanuts; Sesame; Chili",250 kcal,"1. Knead dough with ingredients. 2. Press flat on pan. 3. Make holes; add oil; and roast until crisp."
Telangana,Pacchi Pulusu,https://www.google.com/search?tbm=isch&q=Pacchi+Pulusu,15 mins,"Tamarind water; Onions; Jaggery; Green Chili; Roasted Brinjal (opt)",100 kcal,"1. Extract raw tamarind juice. 2. Add jaggery; onions and salt. 3. Temper with charcoal burnt chili/garlic (No cooking needed)."
Telangana,Golichina Mamsam,https://www.google.com/search?tbm=isch&q=Golichina+Mamsam,45 mins,"Mutton; Onions; Ginger-Garlic; Spices",400 kcal,"1. Boil mutton. 2. Fry (Golichina) in oil with spices until dry and roasted dark brown."
Telangana,Sakinalu,https://www.google.com/search?tbm=isch&q=Sakinalu,45 mins,"Rice Flour; Sesame Seeds; Carom Seeds (Ajwain)",300 kcal,"1. Make dough. 2. Hand-roll into concentric circles. 3. Deep fry. (Famous Makar Sankranti snack)."
Tripura,Mui Borok,https://www.google.com/search?tbm=isch&q=Mui+Borok,40 mins,"Berma (Fermented Fish); Veggies; Rice",150 kcal,"1. The essence of Tripura cuisine. Cook veggies and fish paste without oil. Healthy and organic."
Tripura,Kosoi Bwtwi,https://www.google.com/search?tbm=isch&q=Kosoi+Bwtwi,25 mins,"Beans; Garlic; Ginger; Green Chilies; Berma",120 kcal,"1. Boil beans and tofu (optional). 2. Add crushed garlic and fermented fish. 3. Serve as a semi-dry dish."
Tripura,Gudok,https://www.google.com/search?tbm=isch&q=Gudok+Tripura,30 mins,"Berma; Potatoes; Jackfruit seeds; Bamboo shoot",180 kcal,"1. Mash boiled vegetables. 2. Mix with fermented fish paste and chilies. 3. Cook in bamboo pipes (traditional) or pot."
Tripura,Wahan Mosdeng,https://www.google.com/search?tbm=isch&q=Wahan+Mosdeng,35 mins,"Pork; Onion; Coriander; Green Chili",350 kcal,"1. Boil pork cubes. 2. Mix with chopped raw onions; chilies; and coriander leaves (Pork Salad)."
Tripura,Mosdeng Serma,https://www.google.com/search?tbm=isch&q=Mosdeng+Serma,15 mins,"Red Chilies; Garlic; Tomato; Berma",80 kcal,"1. Roast chilies and garlic. 2. Mash with tomato and fermented fish. 3. Spicy chutney side dish."
Uttar Pradesh,Galouti Kebab,https://www.google.com/search?tbm=isch&q=Galouti+Kebab,60 mins,"Finely Minced Mutton; Raw Papaya; Spices; Rose water",350 kcal,"1. Marinate meat with papaya (tenderizer). 2. Mix secret spices. 3. Shallow fry patties in Ghee. Melts in mouth."
Uttar Pradesh,Tehri,https://www.google.com/search?tbm=isch&q=UP+Tehri,40 mins,"Rice; Potatoes; Cauliflower; Peas; Turmeric",300 kcal,"1. Sauté veggies with spices. 2. Add washed rice and water. 3. Cook until yellow fluffy rice is ready."
Uttar Pradesh,Aloo Bedmi Puri,https://www.google.com/search?tbm=isch&q=Bedmi+Puri+Aloo,50 mins,"Wheat Flour; Urad Dal paste; Potato Curry",450 kcal,"1. Knead dough with urad dal paste. 2. Deep fry pooris. 3. Serve with spicy potato gravy."
Uttar Pradesh,Bharwan Bhindi,https://www.google.com/search?tbm=isch&q=Bharwan+Bhindi,30 mins,"Okra (Ladyfinger); Fennel; Coriander powder; Amchur",200 kcal,"1. Slit okra. 2. Fill with spice mix. 3. Pan fry until cooked and crispy."
Uttar Pradesh,Makhan Malai,https://www.google.com/search?tbm=isch&q=Makhan+Malai+Lucknow,8 hours,"Milk Cream; Saffron; Sugar; Dew (Winter special)",300 kcal,"1. Whip milk cream overnight under the sky. 2. Collect the foam. 3. Serve with saffron and nuts (Nimish)."
Uttarakhand,Kafuli,https://www.google.com/search?tbm=isch&q=Kafuli,35 mins,"Spinach; Fenugreek; Rice paste; Curd",180 kcal,"1. Boil and mash green leaves. 2. Cook with rice paste (thickener). 3. Add curd and temper."
Uttarakhand,Bhatt Ki Churkani,https://www.google.com/search?tbm=isch&q=Bhatt+Ki+Churkani,40 mins,"Black Soybean (Bhatt); Flour; Garlic; Ghee",250 kcal,"1. Roast black soybeans in ghee. 2. Add flour and brown it. 3. Add water and simmer until thick."
Uttarakhand,Aloo Ke Gutke,https://www.google.com/search?tbm=isch&q=Aloo+Ke+Gutke,20 mins,"Boiled Potatoes; Jamboo (Herb); Red Chilies; Coriander",200 kcal,"1. Cut boiled potatoes. 2. Stir fry with Pahadi spices and Jamboo herb. 3. Serve dry with tea."
Uttarakhand,Bal Mithai,https://www.google.com/search?tbm=isch&q=Bal+Mithai,60 mins,"Khoya (Mawa); Cane Sugar; Poppy Seeds",400 kcal,"1. Cook Khoya with sugar until chocolate brown (chocolate fudge like). 2. Cut into cubes. 3. Roll in white poppy seeds."
Uttarakhand,Phanu,https://www.google.com/search?tbm=isch&q=Phanu+Recipe,45 mins,"Gahat Dal (Horse Gram); Ginger; Garlic",220 kcal,"1. Soak and grind dal. 2. Fry some as pancakes; mix rest in water. 3. Boil water mixture; add pancakes and cook."
West Bengal,Macher Jhol,https://www.google.com/search?tbm=isch&q=Macher+Jhol,40 mins,"Rohu Fish; Potato; Tomato; Panch Phoron/Kalonji",280 kcal,"1. Lightly fry fish. 2. Make light gravy with spices and veggies. 3. Simmer fish in gravy."
West Bengal,Kosha Mangsho,https://www.google.com/search?tbm=isch&q=Kosha+Mangsho,90 mins,"Mutton; Mustard Oil; Onions; Yogurt; Sugar",500 kcal,"1. Marinate mutton. 2. Slow cook with caramelized onions and spices for hours until dark and thick."
West Bengal,Luchi Alur Dom,https://www.google.com/search?tbm=isch&q=Luchi+Alur+Dom,45 mins,"Maida (Flour); Potatoes; Spices; Ghee",400 kcal,"1. Make fluffy deep-fried flatbreads (Luchi). 2. Cook spicy potato curry (Alur Dom). 3. Serve together."
West Bengal,Shukto,https://www.google.com/search?tbm=isch&q=Bengali+Shukto,40 mins,"Bitter Gourd; Plantain; Potato; Drumstick; Milk; Poppy Seeds",200 kcal,"1. Fry bitter gourd. 2. Sauté other veggies. 3. Simmer in milk and poppy seed paste. A bitter-sweet starter."
West Bengal,Mishti Doi,https://www.google.com/search?tbm=isch&q=Mishti+Doi,12 hours,"Milk; Sugar/Jaggery; Curd culture",300 kcal,"1. Thicken milk by boiling. 2. Caramelize sugar and add to milk. 3. Add culture and let it set in clay pot overnight."`;

function parseCSV(csv) {
    const lines = csv.split('\n');
    return lines.map(line => {
        if (!line.trim()) return null;
        
        const result = [];
        let current = "";
        let inQuotes = false;
        for (let i = 0; i < line.length; i++) {
            const char = line[i];
            if (char === '"') {
                if (inQuotes && line[i + 1] === '"') {
                    // Escaped quote: "" -> "
                    current += '"';
                    i++; // Skip next quote
                } else {
                    inQuotes = !inQuotes;
                }
            } else if (char === ',' && !inQuotes) {
                result.push(current.trim());
                current = "";
            } else {
                current += char;
            }
        }
        result.push(current.trim());
        
        if (result.length < 7) return null;

        return {
            state: result[0],
            name: result[1],
            image: result[2],
            cookTime: result[3],
            ingredients: result[4],
            calories: result[5],
            steps: result[6]
        };
    }).filter(recipe => recipe !== null);
}

async function migrate() {
    console.log("Starting final comprehensive migration...");
    const recipes = parseCSV(rawData);
    
    try {
        // TRUNCATE with RESTART IDENTITY to ensure IDs start from 1
        console.log("Cleaning table and resetting IDs...");
        await db.execute(sql`TRUNCATE TABLE coustome_recipes RESTART IDENTITY;`);
        
        // Split into chunks if necessary (Drizzle handle large inserts well but good practice)
        const chunkSize = 50;
        for (let i = 0; i < recipes.length; i += chunkSize) {
            const chunk = recipes.slice(i, i + chunkSize);
            await db.insert(coustomeRecipesTable).values(chunk).execute();
            console.log("Inserted chunk " + (Math.floor(i / chunkSize) + 1));
        }
        
        console.log("Migration successful! Total inserted: " + recipes.length + " recipes.");
    } catch (error) {
        console.error("Migration failed:", error);
    }
}

migrate();
