import { db } from "../config/db.js";
import { coustomeRecipesTable } from "./schema.js";
import { sql } from "drizzle-orm";

const rawData = `Andhra Pradesh,Hyderabadi Biryani,https://www.google.com/search?tbm=isch&q=Hyderabadi+Biryani,60 mins,"Basmati Rice; Chicken/Mutton; Yogurt; Onions; Spices; Saffron",400 kcal,"[""Wash the chicken/mutton thoroughly and drain excess water."", ""In a large bowl, mix meat with ginger-garlic paste, turmeric, red chili powder, yogurt, lemon juice, fried onions (birista), chopped mint, coriander, and salt. Marinate for at least 4 hours or overnight."", ""Wash basmati rice and soak it for 30 minutes."", ""Boil a large pot of water with whole spices (bay leaf, cloves, cardamom, shahi jeera) and salt. Add the soaked rice."", ""Cook the rice until it is 70% done (grains should still have a slight bite). Drain the water."", ""In a heavy-bottomed pan (Handi), spread the marinated meat in an even layer at the bottom."", ""Layer the 70% cooked rice over the meat. Do not mix."", ""Sprinkle saffron milk, ghee, remaining fried onions, and mint leaves on top of the rice."", ""Seal the pot with dough or a tight lid/foil to trap steam (Dum cooking)."", ""Cook on high heat for 10 minutes, then lower the heat to the minimum and cook for 40-45 minutes."", ""Turn off heat and let it rest for 15 minutes before opening. Serve hot.""]"
Andhra Pradesh,Gongura Mutton,https://www.google.com/search?tbm=isch&q=Gongura+Mutton+Curry,50 mins,"Mutton; Gongura Leaves (Sorrel); Onions; Green Chilies; Ginger-Garlic Paste",350 kcal,"[""Wash the mutton pieces and pressure cook them with chopped onions, ginger-garlic paste, turmeric, and a little water for 4-5 whistles until soft."", ""Pick the Gongura (sorrel) leaves and wash them well. discard stems."", ""In a pan, heat a little oil and fry the Gongura leaves and green chilies until the leaves shrink and become mushy. Let it cool."", ""Grind the fried Gongura leaves into a coarse paste."", ""In a separate kadhai, heat oil. Add cloves, cardamom, and sliced onions. Sauté until onions turn golden."", ""Add the cooked mutton (keep the stock/water separate) and fry for 5 minutes."", ""Add red chili powder, coriander powder, and salt. Mix well."", ""Add the Gongura paste to the mutton and mix thoroughly."", ""Pour in the leftover mutton stock (water from pressure cooker). adjust consistency."", ""Cover and simmer on low heat for 10-15 minutes until oil floats on top."", ""Serve hot with steamed rice.""]"
Andhra Pradesh,Pesarattu (Green Moong Dosa),https://www.google.com/search?tbm=isch&q=Pesarattu+Dosa,20 mins,"Whole Green Moong Dal; Rice; Ginger; Green Chilies; Cumin; Onions",200 kcal,"[""Wash whole green moong dal and raw rice thoroughly. Soak them together in water for 4 to 6 hours (or overnight)."", ""Drain the water. Transfer the soaked dal and rice into a grinder."", ""Add green chilies, ginger pieces, and cumin seeds into the grinder."", ""Grind to a smooth batter adding very little water. The consistency should be like dosa batter (not too runny)."", ""Add salt to the batter and mix well. (No fermentation is needed, you can use it immediately)."", ""Heat a tawa (griddle) on medium heat. Sprinkle some water and wipe it clean."", ""Pour a ladle full of batter in the center and spread it in a circular motion to make a thin dosa."", ""Drizzle 1 teaspoon of oil around the edges."", ""Sprinkle chopped onions, chopped ginger, and cumin seeds on top of the dosa while it is cooking."", ""Press the onions gently with a spatula so they stick."", ""Cook until the bottom turns golden and crisp. Flip if you like crispier onions, or fold and remove."", ""Serve hot with Upma (optional) and Ginger Chutney.""]"
Andhra Pradesh,Gutti Vankaya Kura (Stuffed Brinjal),https://www.google.com/search?tbm=isch&q=Gutti+Vankaya+Curry,40 mins,"Small Brinjals; Peanuts; Coconut; Sesame Seeds; Tamarind; Onions",280 kcal,"[""Dry roast peanuts, sesame seeds, coriander seeds, cumin seeds, dried coconut, cinnamon, and cloves until aromatic. Cool and grind into a fine powder."", ""Add onion pieces, ginger, garlic, tamarind, and salt to the blender with the spice powder. Grind to a smooth paste adding a little water."", ""Wash small purple brinjals. Slit them in a 'plus' (+) shape from the bottom, keeping the stem intact (don't cut fully)."", ""Stuff the ground masala paste inside each brinjal tightly. Keep remaining paste aside."", ""Heat oil in a deep pan. Add mustard seeds and curry leaves. Let them splutter."", ""Gently place the stuffed brinjals in the oil. Fry them for 5-8 minutes, turning occasionally until the skin blisters slightly."", ""Add the remaining masala paste to the pan and mix gently."", ""Add about 1 cup of water and salt as needed. Bring to a boil."", ""Cover the pan with a lid and cook on low-medium heat for 15-20 minutes."", ""Cook until the brinjals are completely soft and oil separates from the gravy."", ""Garnish with coriander leaves.""]"
Andhra Pradesh,Chepala Pulusu (Fish Curry),https://www.google.com/search?tbm=isch&q=Andhra+Chepala+Pulusu,45 mins,"Fish Pieces; Tamarind Pulp; Onions; Tomatoes; Mustard Seeds; Fenugreek",300 kcal,"[""Soak lemon-sized tamarind in warm water and extract the thick juice (pulp). Discard the fiber."", ""Wash fish pieces carefully with salt and turmeric water. Drain well."", ""Heat oil in a wide, flat pan (fish needs space). Add mustard seeds and fenugreek seeds (methi)."", ""Add chopped onions, green chilies, and curry leaves. Sauté until onions turn golden brown."", ""Add ginger-garlic paste and sauté for a minute until the raw smell goes away."", ""Add turmeric powder, red chili powder (Andhra style needs more spice), and coriander powder."", ""Pour the extracted tamarind juice and add about 1-2 cups of water depending on how thick you want the gravy."", ""Add salt. Bring the gravy to a rolling boil."", ""Gently drop the raw fish pieces into the boiling gravy one by one."", ""Cover the pan and cook on medium heat for 10-12 minutes."", ""IMPORTANT: Do not stir with a spoon as fish will break. Instead, hold the pan handles and swirl/rotate it gently to mix."", ""Cook until the gravy thickens and oil floats on top."", ""Turn off the heat and garnish with fresh coriander. It tastes better if eaten after a few hours.""]"
Arunachal Pradesh,Thukpa,https://www.google.com/search?tbm=isch&q=Arunachal+Thukpa,30 mins,"Noodles; Vegetables (Carrot/Spinach); Chicken (opt); Ginger-Garlic; Soy Sauce",300 kcal,"[""Heat oil in a large pot over medium heat."", ""Add chopped onions, minced ginger, and minced garlic. Sauté until fragrant and onions are translucent."", ""Add chopped vegetables like carrots, cabbage, and beans (and chicken strips if non-veg). Sauté for 2-3 minutes."", ""Pour in vegetable or chicken stock (or water) and bring it to a rolling boil."", ""Add soy sauce, a little vinegar, salt, and black pepper powder."", ""Add the noodles (egg noodles or plain flour noodles) into the boiling broth."", ""Cook until the noodles are soft but not mushy (usually 5-8 minutes)."", ""Turn off the heat. Garnish generously with chopped spring onions and fresh coriander."", ""Serve piping hot in a bowl.""]"
Arunachal Pradesh,Zan (Millet Porridge),https://www.google.com/search?tbm=isch&q=Arunachal+Pradesh+Zan+Recipe,25 mins,"Millet Flour; Water; Vegetables; Smoked Meat (optional); Spices",250 kcal,"[""Dry roast the millet flour (usually finger millet) in a pan on low heat for 2-3 minutes until it releases a nutty aroma."", ""In a separate pot, bring water to a boil."", ""Slowly add the roasted flour into the boiling water while whisking continuously to ensure no lumps form."", ""Add washed and chopped green leafy vegetables (like spinach or cabbage) and green peas."", ""If using meat, add pre-boiled small meat chunks now."", ""Add salt and butter (or ghee) for flavor."", ""Simmer on low heat, stirring occasionally, until the mixture thickens to a porridge consistency."", ""Serve hot, traditionally eaten with fermented soybeans or chutney.""]"
Arunachal Pradesh,Pika Pila,https://www.google.com/search?tbm=isch&q=Pika+Pila+Recipe,15 mins,"Bamboo Shoots; Pork Fat; King Chili (Bhut Jolokia); Salt",100 kcal,"[""Clean the bamboo shoots properly and slice them into thin strips."", ""In a bowl, combine the sliced bamboo shoots with pork fat (lard)."", ""Add a pinch of baking soda (this softens the bamboo shoots and adds flavor)."", ""Add finely chopped King Chili (Bhut Jolokia) or very spicy red chili flakes."", ""Add salt to taste."", ""Mix everything thoroughly using a spoon or gloved hands (King Chili is very hot)."", ""Let it sit for a few hours for flavors to meld, or serve immediately as a spicy pickle-like side dish.""]"
Arunachal Pradesh,Lukter,https://www.google.com/search?tbm=isch&q=Lukter+Recipe+Arunachal,20 mins,"Cooked Dry Meat; King Chili flakes; Ginger; Garlic",200 kcal,"[""Take cooked dry meat (usually beef or pork that has been smoked and dried) and shred it into fine, thin fibrous strips."", ""Heat a tawa or pan lightly."", ""Dry roast dry red chilies (specifically Bhut Jolokia flakes for authenticity) until crisp."", ""Crush the roasted chilies into flakes."", ""In a bowl, mix the shredded dry meat with the chili flakes."", ""Add crushed ginger and garlic cloves for raw pungency."", ""Add salt and toss everything together until the meat is evenly coated with the spices."", ""Serve as a dry accompaniment to rice and curry.""]"
Arunachal Pradesh,Pehak,https://www.google.com/search?tbm=isch&q=Pehak+Recipe,20 mins,"Fermented Soya Bean; King Chili; Salt; Water",120 kcal,"[""Take the fermented soya bean cake or paste (locally available)."", ""Mash the soya beans thoroughly using a mortar and pestle or back of a spoon."", ""Roast dry red chilies (King Chili) over an open flame until charred and smoky, then crush them."", ""Mix the mashed soya beans with the crushed chilies."", ""Add salt to taste."", ""Add a little warm water to the mixture to bring it to a chutney-like consistency."", ""Mix vigorously to combine all flavors."", ""Serve as a spicy, pungent dip with steamed rice and boiled vegetables.""]"
Assam,Masor Tenga,https://www.google.com/search?tbm=isch&q=Masor+Tenga+Recipe,40 mins,"Rohu Fish; Tomatoes; Lemon or Elephant Apple; Turmeric; Mustard Oil",250 kcal,"[""Clean the fish pieces, rub with turmeric and salt, and leave for 15 minutes."", ""Heat mustard oil in a pan and lightly fry the fish pieces. Remove and keep aside."", ""In the same oil, add fenugreek seeds (methi) and let them splutter."", ""Add chopped tomatoes and turmeric powder. Sauté until tomatoes are pulpy."", ""Add about 2 cups of warm water and salt. Bring to a boil."", ""Gently slide the fried fish pieces into the curry."", ""Squeeze fresh lemon juice (or add elephant apple juice) into the curry for sourness."", ""Simmer for 5-7 minutes. Garnish with coriander and serve with rice.""]"
Assam,Khar,https://www.google.com/search?tbm=isch&q=Assamese+Khar+Recipe,35 mins,"Raw Papaya; Pulses; Kol Khar (Banana Peel Ash filtrate); Mustard Oil",180 kcal,"[""Heat mustard oil in a pan. Add crushed garlic cloves."", ""Add chopped raw papaya and washed pulses (black lentils or split peas). Fry for a few minutes."", ""Add water just enough to cover the ingredients and add salt."", ""Cover and cook until the papaya is soft and pulpy."", ""Add the key ingredient 'Kol Khar' (banana peel ash extract) or a pinch of baking soda."", ""Simmer for another 5 minutes until the gravy thickens slightly."", ""Turn off heat and drizzle 1 tablespoon of raw mustard oil on top before serving.""]"
Assam,Duck Meat Curry,https://www.google.com/search?tbm=isch&q=Assamese+Duck+Meat+Curry,60 mins,"Duck Meat; Ash Gourd (Kumura); Black Pepper; Ginger-Garlic; Whole Spices",450 kcal,"[""Clean and cut the duck meat with skin (skin adds flavor). Marinate with turmeric and salt."", ""Heat oil in a pressure cooker or heavy pot. Add whole spices (bay leaf, cardamom, cinnamon)."", ""Add chopped onions and fry until golden brown."", ""Add ginger-garlic paste and sauté for 2 minutes."", ""Add the duck meat and fry on medium heat for 15-20 minutes until oil separates."", ""Add cumin powder, coriander powder, and red chili powder. Mix well."", ""Add chunks of Ash Gourd (Kumura) and black pepper powder."", ""Add warm water and pressure cook for 4-5 whistles (duck takes longer than chicken).""]"
Assam,Aloo Pitika,https://www.google.com/search?tbm=isch&q=Aloo+Pitika,15 mins,"Potatoes; Mustard Oil; Onions; Green Chilies; Salt; Coriander",150 kcal,"[""Boil potatoes until they are completely soft."", ""Peel the potatoes and mash them thoroughly in a bowl."", ""Add finely chopped raw onions."", ""Add finely chopped green chilies and fresh coriander leaves."", ""Add salt to taste."", ""Pour a generous amount of raw mustard oil (this is crucial for the authentic pungent flavor)."", ""Mix everything together with your hand until well combined."", ""Serve immediately as a side dish with rice and dal.""]"
Assam,Koldil Inkura,https://www.google.com/search?tbm=isch&q=Chicken+with+Banana+Flower+Assam,50 mins,"Chicken; Banana Flower (Koldil); Potatoes; Ginger-Garlic; Spices",300 kcal,"[""Finely chop the Banana Flower (Koldil) and soak in water to prevent browning."", ""Boil the chopped flower with a little salt and turmeric, then drain the water (removes bitterness)."", ""Heat oil in a pan. Add chopped onions and bay leaves."", ""Add chicken or duck meat pieces and sauté until browned."", ""Add ginger-garlic paste, cumin, and coriander powder."", ""Add the boiled banana flower and cubed potatoes."", ""Cover and cook on low heat. Do not add much water; let it cook in its own juices until dry and tender.""]"
Bihar,Litti Chokha,https://www.google.com/search?tbm=isch&q=Litti+Chokha,70 mins,"Wheat Flour; Sattu; Brinjal; Tomato; Garlic; Mustard Oil; Ghee",400 kcal,"[""Dough: Mix wheat flour, ghee, and salt. Knead into a firm dough with water."", ""Filling (Sattu): Mix Sattu (roasted gram flour) with chopped garlic, ginger, green chilies, coriander, onion, mustard oil, pickle masala (achaar), ajwain, and lemon juice."", ""Take a dough ball, flatten it, create a cup shape, stuff the Sattu mixture, and seal it tight into a round ball."", ""Chokha: Roast eggplant (brinjal) and tomatoes over direct flame until skin chars. Peel and mash them. Add chopped onions, chilies, garlic, mustard oil, and salt."", ""Bake the Littis over a coal barbecue (Goitha) or in an oven at 200°C until the crust is brown and hard."", ""Dip the hot Littis in melted Ghee completely."", ""Serve with the Chokha and green chutney.""]"
Bihar,Sattu Paratha,https://www.google.com/search?tbm=isch&q=Sattu+Paratha,30 mins,"Wheat Flour; Sattu (Roasted Gram Flour); Ajwain; Pickle Masala; Onion",280 kcal,"[""Prepare the filling: In a bowl, mix Sattu, finely chopped onion, garlic, ginger, green chilies, kalonji (nigella seeds), ajwain, mustard oil, pickle masala, lemon juice, and salt."", ""Knead a soft dough using whole wheat flour and water."", ""Take a lemon-sized portion of dough, roll it slightly, place the sattu filling in the center, and seal the edges."", ""Roll out the stuffed dough gently into a flat circle (Paratha)."", ""Heat a tawa (griddle). Place the paratha on it."", ""Cook one side, flip, and apply oil or ghee."", ""Flip again and apply oil/ghee on the other side. Cook until golden brown spots appear."", ""Serve hot with curd or pickle.""]"
Bihar,Champaran Meat,https://www.google.com/search?tbm=isch&q=Champaran+Meat,90 mins,"Mutton; Whole Garlic Bulbs; Mustard Oil; Onions; Whole Spices",500 kcal,"[""In a large bowl, take the raw mutton pieces."", ""Add sliced onions, ginger-garlic paste, turmeric, coriander powder, red chili powder, cumin powder, whole spices (garam masala), and salt."", ""Pour raw mustard oil over the meat."", ""Add 2-3 whole garlic bulbs (wash them, do not peel) into the mix."", ""Mix everything thoroughly with your hands."", ""Transfer the mixture into an earthen pot (Handi)."", ""Cover the mouth of the pot with a clay lid and seal the edges with wheat dough."", ""Place the pot on a charcoal fire (or low gas flame) and cook for 60-90 minutes."", ""Shake the pot every 15 minutes to prevent sticking. Do not open until done.""]"
Bihar,Thekua,https://www.google.com/search?tbm=isch&q=Thekua+Recipe,40 mins,"Wheat Flour; Jaggery/Sugar; Ghee; Coconut; Cardamom",350 kcal,"[""In a large bowl, mix whole wheat flour and grated coconut (and fennel seeds if desired)."", ""Add ghee to the flour and rub it with your fingers until it resembles breadcrumbs (Moyen)."", ""Dissolve sugar or jaggery in a little warm water."", ""Add the sweet water to the flour mixture gradually."", ""Knead a very stiff and hard dough (do not make it soft)."", ""Pinch small balls of dough. Press them against a wooden 'Thekua mold' to get a design, or flatten by hand."", ""Heat oil or ghee in a deep pan on low flame."", ""Deep fry the Thekuas on low heat until they turn dark brown and crispy (cooking on high heat will leave them raw inside)."", ""Cool completely to harden before storing.""]"
Bihar,Chana Ghugni,https://www.google.com/search?tbm=isch&q=Bihari+Chana+Ghugni,40 mins,"Black Chickpeas (Kala Chana); Onions; Tomatoes; Ginger-Garlic; Spices",220 kcal,"[""Soak black chickpeas (Kale Chane) overnight. Pressure cook for 3-4 whistles."", ""Heat oil in a pan. Add cumin seeds and bay leaf."", ""Add onion paste (or finely chopped onions) and fry until golden."", ""Add ginger-garlic paste, turmeric, coriander powder, meat masala (optional), and red chili powder."", ""Add chopped tomatoes and salt. Cook until oil separates from the masala."", ""Add the boiled chickpeas along with a little of the boiled water."", ""Cover and cook for 10 minutes so chickpeas absorb the flavor."", ""Garnish with fresh coriander. Serve with puffed rice (Muri) or Chuda.""]"
Chhattisgarh,Chila,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Chila+Recipe,20 mins,"Rice Flour; Urad Dal paste; Water; Green Chilies; Coriander; Salt",150 kcal,"[""Take rice flour in a bowl."", ""Add a small amount of Urad dal paste (optional, for softness) or just use plain rice flour."", ""Add water gradually to make a smooth pouring batter (consistency like Dosa or slightly thinner)."", ""Add salt, finely chopped green chilies, and chopped coriander leaves to the batter."", ""Heat a tawa (griddle) and brush with oil."", ""Pour a ladle full of batter and spread it gently (it is usually thicker than a dosa)."", ""Cover with a lid for 2 minutes to let it steam cook."", ""Remove lid, drizzle oil, flip, and cook the other side until crispy spots appear."", ""Serve hot with tomato chutney.""]"
Chhattisgarh,Fara,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Fara+Recipe,40 mins,"Cooked Rice/Rice Flour; Sesame Seeds; Green Chilies; Mustard Seeds",200 kcal,"[""Make a dough using leftover cooked rice and rice flour (mix and knead well with hot water and salt)."", ""Add sesame seeds and carom seeds (ajwain) to the dough."", ""Take small portions of the dough and roll them between your palms to make finger-like cylindrical shapes."", ""Grease a steamer plate. Arrange the rolls (Fara) on it."", ""Steam for 15-20 minutes until they are firm and cooked."", ""Heat oil in a pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Add the steamed Fara and sauté for 3-4 minutes until slightly crispy on the outside."", ""Serve as a snack.""]"
Chhattisgarh,Dubki Kadhi,https://www.google.com/search?tbm=isch&q=Dubki+Kadhi+Recipe,45 mins,"Curd/Yogurt; Gram Flour (Besan); Urad Dal (for dumplings); Curry Leaves",250 kcal,"[""Soak Urad Dal for 4 hours. Grind it into a thick, fluffy paste with ginger and green chili."", ""In a deep pot, whisk sour curd (yogurt) with gram flour (besan), turmeric, and water to make a thin Kadhi liquid."", ""Bring the Kadhi mixture to a boil on medium heat."", ""Once the Kadhi is boiling, wet your hands, take small portions of the thick Urad dal paste, and drop them directly into the boiling liquid (these dumplings are called 'Dubki')."", ""Do not stir immediately. Let the dumplings cook and firm up in the boiling liquid for 10 minutes."", ""Prepare a tempering (tadka) of mustard seeds, dry red chilies, and curry leaves in oil."", ""Pour the tempering over the Kadhi.""]"
Chhattisgarh,Bafauri,https://www.google.com/search?tbm=isch&q=Bafauri+Recipe,30 mins,"Chana Dal; Onions; Ginger-Garlic; Turmeric; Coriander",180 kcal,"[""Soak Chana Dal (split chickpeas) for 3-4 hours."", ""Drain water and grind it coarsely (do not make a fine paste) with ginger and chilies."", ""Add finely chopped onions, turmeric, chili powder, coriander leaves, and salt to the paste. Mix well."", ""Grease a steamer plate or Idli stand."", ""Make small balls of the mixture and place them in the steamer."", ""Steam for 20-25 minutes until a knife inserted comes out clean."", ""Serve these steamed healthy balls with chutney (can be eaten as is, without frying). ""]"
Chhattisgarh,Muthia,https://www.google.com/search?tbm=isch&q=Chhattisgarh+Muthia,35 mins,"Rice batter; Sesame Seeds; Mustard Seeds; Chilies; Curry Leaves",220 kcal,"[""Take cooked rice (mashed) or rice flour in a bowl."", ""Add besan (gram flour), ginger-chili paste, turmeric, sesame seeds, and fenugreek leaves (methi)."", ""Add salt and a little oil. Knead into a soft dough."", ""Grease your hands and shape the dough into cylindrical rolls."", ""Steam the rolls in a steamer for 20 minutes."", ""Let them cool slightly, then cut them into 1-inch round slices."", ""Heat oil in a pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Add the sliced Muthia pieces and sauté until they turn golden and crispy.""]"
Goa,Goan Fish Curry,https://www.google.com/search?tbm=isch&q=Goan+Fish+Curry,35 mins,"Kingfish/Pomfret; Coconut; Kashmiri Chillies; Tamarind; Turmeric",320 kcal,"[""Clean and wash the fish slices (Kingfish or Pomfret). Rub with salt and turmeric."", ""Grind fresh grated coconut, coriander seeds, cumin, garlic, Kashmiri red chilies, and turmeric into a very fine paste using a little water."", ""Heat a little oil in a pot and sauté sliced onions until soft."", ""Add the ground coconut spice paste to the pot and cook for 2 minutes."", ""Add water to adjust the consistency (not too thin, not too thick) and bring to a boil."", ""Split green chilies and add them."", ""Add tamarind pulp (or kokum) and salt. Let it simmer for a minute."", ""Gently slide the fish slices into the curry."", ""Simmer on low heat for 5-7 minutes. Do not overcook or the fish will break."", ""Turn off heat and serve with steamed rice.""]"
Goa,Chicken Xacuti,https://www.google.com/search?tbm=isch&q=Chicken+Xacuti,55 mins,"Chicken; Roasted Coconut; Poppy Seeds; Dried Red Chilies; Star Anise",400 kcal,"[""Clean chicken pieces and marinate with salt, turmeric, and ginger-garlic paste."", ""Roast grated fresh coconut, dried red chilies, poppy seeds, sesame seeds, coriander seeds, cloves, cinnamon, and star anise in a pan until fragrant and coconut turns golden brown."", ""Cool the roasted ingredients and grind them into a smooth Xacuti paste."", ""Heat oil in a heavy-bottomed pan. Sauté chopped onions until golden."", ""Add the marinated chicken and sear on high heat for 3-4 minutes."", ""Add the ground Xacuti paste and mix well with the chicken."", ""Add water and salt. Cover and cook on medium heat until chicken is tender."", ""Add a pinch of nutmeg powder at the end for aroma."", ""Garnish with coriander and serve with Poi (Goan bread) or rice.""]"
Goa,Pork Vindaloo,https://www.google.com/search?tbm=isch&q=Goan+Pork+Vindaloo,60 mins,"Pork Meat; Vinegar; Garlic; Ginger; Kashmiri Chilies; Cumin",500 kcal,"[""Grind dried Kashmiri red chilies, cumin seeds, peppercorns, cloves, cinnamon, ginger, garlic, and turmeric using Vinegar (do not use water) into a smooth paste."", ""Cut pork (with some fat) into cubes. Rub the ground paste and salt over the meat."", ""Marinate the pork for at least 6-8 hours (or overnight) in the fridge."", ""Heat oil in a pan. Add sliced onions and fry until brown."", ""Add the marinated pork along with the marinade paste."", ""Sear the meat on high heat for 5 minutes."", ""Add a little water (optional, as pork releases fat/juice) and extra vinegar if needed."", ""Cover and cook on low heat for 45-60 minutes until the meat is fork-tender."", ""The dish should have a layer of oil/fat floating on top. Serve with rice or bread.""]"
Goa,Bebinca,https://www.google.com/search?tbm=isch&q=Goan+Bebinca,4 hours,"All-Purpose Flour; Coconut Milk; Egg Yolks; Sugar; Ghee; Nutmeg",350 kcal,"[""Extract thick coconut milk from grated coconut."", ""In a bowl, mix sugar and egg yolks until creamy."", ""Add the coconut milk and flour to the yolk mixture. Mix until smooth batter forms. Add nutmeg powder."", ""Preheat the oven (or use a grill). Grease a baking tin with ghee."", ""Pour a thin layer (approx 1/2 cup) of batter into the tin. Bake/Grill until the top is golden brown."", ""Remove from oven, brush melted ghee on the baked layer."", ""Pour another thin layer of batter on top of the first baked layer."", ""Bake again until golden. Repeat this process for 7 to 16 layers."", ""Cool completely before unmolding. Slice and serve.""]"
Goa,Sorpotel,https://www.google.com/search?tbm=isch&q=Goan+Sorpotel,60 mins,"Pork Meat & Liver; Vinegar; Dried Chilies; Spices; Ginger-Garlic",450 kcal,"[""Boil the large pieces of pork meat and liver with little water and salt for 20 minutes. Drain and keep the stock."", ""Cut the parboiled meat and liver into tiny, small cubes."", ""Heat oil in a pan and shallow fry the meat cubes until light brown. Remove and keep aside."", ""In the same oil, fry the Sorpotel masala paste (made by grinding red chilies, garlic, ginger, cloves, cinnamon, cumin, and vinegar)."", ""Add the fried meat cubes to the masala."", ""Add the reserved stock water and more vinegar (Sorpotel is tangy)."", ""Simmer on low heat for 30-40 minutes until the gravy thickens."", ""It tastes best if matured for 2-3 days before serving.""]"
Gujarat,Khaman Dhokla,https://www.google.com/search?tbm=isch&q=Khaman+Dhokla,25 mins,"Gram Flour (Besan); Yogurt; Eno/Soda; Mustard Seeds; Green Chilies",160 kcal,"[""In a bowl, mix besan (gram flour), semolina (suji), lemon juice, ginger-green chili paste, sugar, and salt."", ""Add water gradually to make a smooth, lump-free batter (pouring consistency)."", ""Let the batter rest for 15 minutes."", ""Just before steaming, add Fruit Salt (Eno) or baking soda to the batter and whisk briskly for 10 seconds (batter will froth up)."", ""Immediately pour into a greased thali/plate."", ""Steam in a steamer/cooker for 15-20 minutes on high flame."", ""Insert a knife to check; if it comes out clean, it's done. Let it cool slightly."", ""Tempering: Heat oil, add mustard seeds, sesame seeds, curry leaves, and green chilies. Add 1/2 cup water and sugar to the oil and boil."", ""Cut Dhokla into squares and pour the tempering water over it (this makes it juicy)."", ""Garnish with coriander and fresh coconut.""]"
Gujarat,Undhiyu,https://www.google.com/search?tbm=isch&q=Undhiyu+Recipe,60 mins,"Mixed Winter Vegetables (Papdi; Potato; Yam); Muthiya (Fenugreek balls); Spices",400 kcal,"[""Prepare Muthiya: Mix besan, fenugreek leaves, spices, and oil. Shape into small ovals and fry them."", ""Make a green masala paste: Grind coconut, coriander, green chilies, ginger, garlic, and sugar."", ""Slit small brinjals and potatoes (without cutting fully). Stuff them with the green masala."", ""Heat plenty of oil in a heavy pot. Add carom seeds (ajwain)."", ""Layer the vegetables: Add beans (surti papdi), yam (kand), and raw banana first."", ""Add the stuffed potatoes and brinjals on top."", ""Sprinkle the remaining green masala, salt, and a little water."", ""Cover tightly and slow cook for 30 minutes."", ""Add the fried Muthiya on top in the last 10 minutes of cooking (so they don't break)."", ""Garnish with coriander and serve with Puri.""]"
Gujarat,Thepla,https://www.google.com/search?tbm=isch&q=Methi+Thepla,20 mins,"Wheat Flour; Fenugreek Leaves (Methi); Yogurt; Sesame Seeds; Spices",220 kcal,"[""In a large bowl, take whole wheat flour."", ""Add finely chopped fresh fenugreek leaves (methi)."", ""Add yogurt (curd), sesame seeds, turmeric, red chili powder, coriander powder, sugar, and salt."", ""Add a tablespoon of oil."", ""Knead into a soft dough. Use a little water only if needed (methi releases water)."", ""Pinch small balls and roll them into thin circles (thinner than roti) using dry flour."", ""Heat a tawa. Place the Thepla on it."", ""Flip when bubbles appear. Apply oil on both sides."", ""Press with a spatula and cook until brown spots appear."", ""Serve with pickle and curd.""]"
Gujarat,Khandvi,https://www.google.com/search?tbm=isch&q=Gujarati+Khandvi,40 mins,"Gram Flour; Yogurt; Turmeric; Mustard Seeds; Coconut",180 kcal,"[""In a bowl, whisk besan (gram flour) and sour buttermilk (or yogurt + water) until completely smooth with no lumps."", ""Add turmeric and salt."", ""Pour mixture into a non-stick pan. Cook on low heat, stirring CONSTANTLY."", ""The mixture will thicken into a paste. Cook until it leaves the sides of the pan (takes 8-10 mins)."", ""Quickly spread the hot paste thinly on the back of greased plates or a clean countertop using a spatula."", ""Let it cool for 5 minutes."", ""Cut into strips and roll them up tightly."", ""Tempering: Heat oil, add mustard seeds, sesame seeds, green chilies, and curry leaves."", ""Pour tempering over the rolls. Garnish with coriander and grated coconut.""]"
Gujarat,Handvo,https://www.google.com/search?tbm=isch&q=Gujarati+Handvo,50 mins,"Rice & Lentil Batter; Bottle Gourd; Spices; Sesame Seeds",250 kcal,"[""Wash and soak rice and mixed dals (toor, chana, urad) for 4-5 hours."", ""Grind to a coarse batter (like idli batter). Ferment overnight (or 8 hours)."", ""Add grated bottle gourd (lauki), ginger-chili paste, turmeric, sugar, salt, and a little oil to the fermented batter."", ""Add a pinch of baking soda just before cooking."", ""Heat oil in a heavy pan. Add mustard seeds, sesame seeds, and curry leaves."", ""Pour a thick layer of batter into the pan."", ""Cover and cook on very low heat for 10-15 minutes until the bottom is crisp and golden."", ""Carefully flip and cook the other side."", ""Serve slices with chutney.""]"
Haryana,Bajra Khichdi,https://www.google.com/search?tbm=isch&q=Bajra+Khichdi+Haryana,50 mins,"Bajra (Pearl Millet); Moong Dal; Ghee; Salt; Water",350 kcal,"[""Wash Bajra (Pearl Millet) and Moong Dal separately. Soak bajra for 4-6 hours (helps cooking)."", ""In a pressure cooker, add the soaked bajra, dal, and 4 cups of water."", ""Add salt."", ""Pressure cook for 4-5 whistles on medium heat. Then simmer on low for 10 minutes."", ""Open the cooker once pressure releases. Mash the mixture with a ladle or wooden masher until creamy."", ""If it's too thick, add boiling water and simmer."", ""Serve piping hot with a big dollop of Desi Ghee (crucial for taste) and curd.""]"
Haryana,Haryanvi Churma,https://www.google.com/search?tbm=isch&q=Haryanvi+Roti+Churma,30 mins,"Wheat Flour; Ghee; Bura (Powdered Sugar) or Jaggery",500 kcal,"[""Knead whole wheat flour with water to make a step-by-step instructions stiff dough."", ""Roll out thick rotis (bread)."", ""Cook the rotis on a tawa (or clay oven) until fully cooked and slightly crisp."", ""While the rotis are still very hot, break them into pieces in a large bowl."", ""Add a generous amount of melted Ghee and Bura (powdered sugar) or crushed Jaggery."", ""Crush everything together using your hands (this is the traditional way) until it turns into a coarse crumble."", ""Make ladoos or serve as loose crumble. Eat warm.""]"
Haryana,Kadhi Pakora,https://www.google.com/search?tbm=isch&q=Haryanvi+Kadhi+Pakora,45 mins,"Sour Curd (Lassi); Besan (Gram Flour); Spices; Methi Seeds; Oil",300 kcal,"[""Pakora: Mix besan, chopped onion, spices, and water to make thick batter. Deep fry small fritters (pakoras) in oil."", ""Kadhi Base: In a bowl, whisk sour yogurt and besan with water to make a lump-free thin liquid."", ""Heat oil in a deep pot. Add fenugreek seeds (methi), cumin, and dried red chilies."", ""Pour the yogurt-besan mixture into the pot. Stir continuously until it boils (to prevent curdling)."", ""Add turmeric, salt, and red chili powder."", ""Simmer on low heat for at least 30-40 minutes (the longer it cooks, the better)."", ""Add the fried pakoras to the boiling Kadhi and cook for another 5 minutes."", ""Finish with a second tempering of ghee and red chili powder on top.""]"
Haryana,Bajre Ki Roti & Lasun Chatni,https://www.google.com/search?tbm=isch&q=Bajre+Ki+Roti+Lasun+Chutney,35 mins,"Bajra Flour; Garlic; Dry Red Chilies; Salt; Butter (White Makhan)",350 kcal,"[""Roti: Take Bajra flour, add a pinch of salt. Add hot water gradually."", ""Knead firmly with the palm of your hand until the dough is soft and pliable."", ""Take a portion, dust with dry flour, and pat it between your palms to flatten it (traditional method) or roll gently."", ""Place on a hot tawa. Cook one side, flip, and apply water lightly on top (prevents cracking)."", ""Roast on open flame until puffed and brown spots appear."", ""Chatni: In a mortar and pestle, crush garlic cloves, dry red chilies, and salt together into a coarse paste."", ""Add a little curd or water to adjust consistency."", ""Serve the hot Roti with a big spoon of white butter (Makhan) and the garlic chutney.""]"
Haryana,Bathua Raita,https://www.google.com/search?tbm=isch&q=Bathua+Raita+Recipe,20 mins,"Bathua Leaves (Chenopodium); Curd/Yogurt; Roasted Cumin; Black Salt",120 kcal,"[""Pick the leaves of Bathua (Chenopodium) and wash thoroughly (it holds soil)."", ""Boil the leaves in a little water for 5-7 minutes until soft."", ""Drain and grind the leaves into a smooth paste."", ""In a bowl, whisk fresh curd (dahi) until smooth."", ""Add the Bathua paste to the curd."", ""Add roasted cumin powder, black salt, and red chili powder. Mix well."", ""(Optional) You can add a tempering of cumin seeds in ghee."", ""Serve chilled as a side dish.""]"
Himachal Pradesh,Chana Madra,https://www.google.com/search?tbm=isch&q=Himachali+Chana+Madra,50 mins,"Chickpeas (Kabuli Chana); Yogurt; Ghee; Cloves; Cardamom; Turmeric",400 kcal,"[""Soak Kabuli Chana (chickpeas) overnight and pressure cook until soft."", ""Heat ghee (generously) in a thick-bottomed pan."", ""Add cloves, cinnamon, cardamom, cumin, and coriander powder to the hot ghee."", ""In a bowl, whisk the yogurt (curd) until smooth."", ""Pour the yogurt into the pan and STIR CONTINUOUSLY. This is crucial to prevent the yogurt from curdling."", ""Cook until the yogurt releases oil."", ""Add turmeric and the boiled chickpeas to the mixture."", ""Simmer on low heat for 15-20 minutes until the gravy thickens and absorbs the flavor."", ""Garnish with dry fruits (raisins/cashews) and serve with rice.""]"
Himachal Pradesh,Siddu,https://www.google.com/search?tbm=isch&q=Himachali+Siddu+Recipe,90 mins,"Wheat Flour; Yeast; Poppy Seeds/Walnuts (filling); Ghee",350 kcal,"[""Dissolve yeast and sugar in warm water. Mix with wheat flour and salt to knead a soft dough. Let it rest for 2-4 hours to rise."", ""Grind poppy seeds (khus khus), walnuts, or peanuts into a coarse paste."", ""Mix the paste with green chilies, coriander, ginger, garlic, and salt to make the stuffing."", ""Punch down the risen dough. Take a ball, flatten it, and place the stuffing in the center."", ""Fold it into a semi-circle (calzone shape) and seal the edges."", ""Place the Siddu in a steamer and steam for 15-20 minutes."", ""Serve hot with a generous amount of melted Ghee and green chutney.""]"
Himachal Pradesh,Babru,https://www.google.com/search?tbm=isch&q=Himachali+Babru,40 mins,"Whole Wheat Flour; Black Gram Dal (Urad); Oil; Spices",300 kcal,"[""Soak black gram (urad dal) overnight. Drain and grind to a coarse paste."", ""Add salt and spices to the dal paste."", ""Knead a dough using whole wheat flour and water."", ""Take a small ball of dough, make a hollow, and stuff a spoon of dal paste inside."", ""Seal the ball and roll it out gently like a Puri (don't roll too thin)."", ""Heat oil in a kadhai."", ""Deep fry the Babru until it puffs up and turns golden brown."", ""Serve with tamarind chutney or vegetable curry.""]"
Himachal Pradesh,Tudkiya Bhath,https://www.google.com/search?tbm=isch&q=Tudkiya+Bhath,50 mins,"Rice; Lentils (Masoor); Potatoes; Yogurt; Tomatoes; Cinnamon; Cardamom",320 kcal,"[""Soak rice and masoor dal (lentils) for 30 minutes."", ""Grind garlic, ginger, cardamom, cinnamon, and cloves into a paste."", ""Heat oil/ghee in a cooker. Add bay leaves and the ground spice paste."", ""Add sliced onions and fry. Add chopped tomatoes and cook until soft."", ""Add chopped potatoes and yogurt. Cook for a few minutes."", ""Add the soaked rice and dal."", ""Add water (usually double the quantity of rice) and salt."", ""Pressure cook for 2 whistles."", ""Serve with a squeeze of lemon juice.""]"
Himachal Pradesh,Chha Gosht,https://www.google.com/search?tbm=isch&q=Chha+Gosht+Himachal,70 mins,"Lamb/Mutton; Buttermilk; Gram Flour (Besan); Ginger-Garlic; Coriander",450 kcal,"[""Marinate mutton pieces with ginger-garlic paste and salt."", ""Heat oil in a heavy pot. Add whole spices and gram flour (besan). Roast briefly."", ""Add the marinated mutton and fry until browned."", ""Add coriander powder, red chili powder, and turmeric."", ""Whisk buttermilk (Chha) properly."", ""Add the buttermilk to the pot and stir continuously until it boils."", ""Cover and slow cook for 45-60 minutes until the meat is tender and the gravy is thick and rich."", ""Serve with rice.""]"
Jharkhand,Dhuska,https://www.google.com/search?tbm=isch&q=Dhuska+Jharkhand,40 mins,"Rice; Chana Dal; Urad Dal; Green Chilies; Cumin",250 kcal,"[""Soak rice and chana dal (split chickpeas) together for 4-5 hours."", ""Drain and grind them with green chilies and ginger to a slightly coarse, thick batter."", ""Add cumin seeds, turmeric, and salt to the batter. Mix well."", ""Let the batter ferment/rest for 1-2 hours."", ""Heat oil in a deep frying pan."", ""Pour a ladleful of batter gently into the hot oil (do not spread it)."", ""It will puff up like a poori. Cook on medium flame until golden brown on both sides."", ""Drain oil and serve with Ghugni (chickpea curry) or Aloo Dum.""]"
Jharkhand,Rugra,https://www.google.com/search?tbm=isch&q=Rugra+Recipe,35 mins,"Rugra (Local Mushroom); Onions; Tomatoes; Garlic; Spices",180 kcal,"[""Wash the Rugra (local mushrooms) thoroughly multiple times to remove soil. Cut them into halves."", ""Heat mustard oil in a pan. Add cumin seeds and bay leaf."", ""Add chopped onions and fry until golden brown."", ""Add ginger-garlic paste and tomato puree. Sauté until oil separates."", ""Add turmeric, meat masala (optional), and chili powder."", ""Add the Rugra pieces and salt. Mix well."", ""Cover and cook on low heat. Rugra releases water, so let it cook in its own juices initially."", ""Add a little warm water if needed and simmer until Rugra is tender and has a meat-like texture.""]"
Jharkhand,Chilka Roti,https://www.google.com/search?tbm=isch&q=Chilka+Roti,25 mins,"Rice Flour; Chana Dal; Water; Salt",200 kcal,"[""Soak rice and chana dal for 4 hours."", ""Grind them into a smooth batter (consistency similar to Dosa batter)."", ""Add salt to the batter."", ""Heat a tawa (griddle) and grease lightly with oil."", ""Pour a ladle of batter and spread it slightly (it is thicker than a dosa)."", ""Cover with a lid and cook for 2 minutes."", ""Flip and cook the other side for a minute."", ""Serve hot with mutton curry or chana dal.""]"
Jharkhand,Bamboo Shoot Curry,https://www.google.com/search?tbm=isch&q=Bamboo+Shoot+Curry+Jharkhand,30 mins,"Fermented Bamboo Shoots; Mustard Oil; Garlic; Red Chilies",150 kcal,"[""Take fermented bamboo shoots (karil). Wash them well."", ""Soak them in warm water for 15 minutes to reduce strong smell, then drain."", ""Heat mustard oil in a pan."", ""Add crushed garlic cloves and dry red chilies. Fry until garlic is brown."", ""Add the bamboo shoots and turmeric powder."", ""Stir fry on low heat for 10-15 minutes."", ""Add salt and cook until the moisture evaporates and shoots are tender."", ""Serve as a side dish with rice.""]"
Jharkhand,Arsa Roti,https://www.google.com/search?tbm=isch&q=Arsa+Roti,40 mins,"Rice Flour; Jaggery Syrup; Sesame Seeds; Oil",350 kcal,"[""Soak rice for 3-4 hours. Drain and dry it on a cloth for 30 minutes."", ""Grind the semi-wet rice into a fine powder."", ""In a pan, boil jaggery with a little water to make a syrup. (Check consistency: soft ball stage)."", ""Turn off the flame and immediately add the rice flour to the hot syrup."", ""Mix vigorously to form a dough."", ""Grease your palms with oil. Take small portions of the warm dough."", ""Flatten them into small thick discs and press sesame seeds on top."", ""Deep fry in hot oil on medium heat until dark brown."", ""Cool to store (they harden as they cool).""]"
Karnataka,Bisi Bele Bath,https://www.google.com/search?tbm=isch&q=Bisi+Bele+Bath,50 mins,"Rice; Toor Dal; Tamarind; Jaggery; Vegetables; Spice Powder",350 kcal,"[""Pressure cook rice and toor dal together with turmeric and a little oil until very soft and mushy."", ""In a separate pot, boil mixed vegetables (carrot, beans, peas) until cooked."", ""Soak tamarind and extract juice."", ""In a large pan, mix the cooked rice-dal mash and boiled vegetables."", ""Add tamarind extract, jaggery, salt, and water to adjust consistency (should be porridge-like)."", ""Add Bisi Bele Bath Masala powder (store-bought or homemade). Mix well."", ""Simmer on low heat for 10 minutes."", ""Tempering: Fry cashew nuts, mustard seeds, curry leaves, and dry red chilies in abundant Ghee."", ""Pour tempering over the rice. Serve hot with Kara Boondi.""]"
Karnataka,Mysore Masala Dosa,https://www.google.com/search?tbm=isch&q=Mysore+Masala+Dosa,40 mins,"Rice-Urad Batter; Red Chutney (Garlic-Chili); Potato Bhaji; Butter",320 kcal,"[""Soak rice, urad dal, chana dal, and methi seeds. Grind to a batter and ferment overnight."", ""Red Chutney: Grind roasted gram, dried red chilies, garlic, and tamarind to a thick paste."", ""Potato Palya: Boil and mash potatoes. Sauté with mustard seeds, turmeric, onions, and curry leaves."", ""Heat a tawa. Pour batter and spread it into a circle."", ""Drizzle ghee/butter around the edges."", ""Once the bottom starts browning, smear a spoonful of Red Chutney all over the inside surface."", ""Place a portion of Potato Palya in the center."", ""Fold the dosa into a roll or triangle."", ""Serve with coconut chutney and sambar.""]"
Karnataka,Ragi Mudde,https://www.google.com/search?tbm=isch&q=Ragi+Mudde,25 mins,"Ragi (Finger Millet) Flour; Water; Ghee",180 kcal,"[""In a heavy-bottomed vessel, boil 2 cups of water with a teaspoon of ghee and salt."", ""Take 1 cup of Ragi (Finger Millet) flour."", ""Sprinkle a little flour into the boiling water first."", ""Then pour the rest of the flour into the center of the boiling water. Do not stir yet. Let it boil for 2 mins."", ""Now, use a strong wooden stick (mudde stick) to stir vigorously."", ""Break all lumps and cook until the mixture leaves the sides of the pan and becomes a shiny ball."", ""Transfer the hot mixture to a wet plate."", ""Dip your hands in cold water and quickly shape the hot mixture into smooth balls."", ""Serve immediately with Bassaru or Chicken curry. (Swallow, do not chew). ""]"
Karnataka,Neer Dosa,https://www.google.com/search?tbm=isch&q=Neer+Dosa,20 mins,"Rice; Coconut; Salt; Water",140 kcal,"[""Soak raw rice for 4-5 hours."", ""Grind the rice with fresh grated coconut and a little water to a very smooth paste."", ""Add plenty of water to the batter. The consistency should be very watery (like milk), much thinner than regular dosa batter."", ""Add salt. No fermentation required."", ""Heat a non-stick tawa. Do not grease heavily."", ""Pour a ladle of watery batter onto the pan (do not spread with a spoon, just tilt the pan to cover holes)."", ""Cover with a lid immediately."", ""Cook for 1 minute on medium flame. Do not flip (cook only one side)."", ""Fold it into a triangle on the tawa itself and remove."", ""Serve with coconut jaggery mixture or spicy curry.""]"
Karnataka,Mysore Pak,https://www.google.com/search?tbm=isch&q=Mysore+Pak,40 mins,"Gram Flour (Besan); Sugar; Ghee (Lots of it)",500 kcal,"[""Sift the Besan (gram flour) to remove lumps."", ""Heat 1 cup of ghee in a pan. Add the besan and roast slightly."", ""In another heavy pan, dissolve sugar in water and boil to reach 'one string consistency'."", ""Slowly add the besan mixture to the sugar syrup, stirring continuously."", ""Keep a separate pan of ghee hot on the side."", ""Add a ladle of hot ghee to the mixture while stirring. The mixture will froth."", ""Repeat adding hot ghee and stirring until the mixture becomes porous and starts leaving the pan."", ""Pour quickly into a greased tray."", ""Let it cool partially, then cut into squares.""]"
Kerala,Appam with Stew,https://www.google.com/search?tbm=isch&q=Appam+Stew,45 mins,"Rice Flour; Coconut Milk; Yeast; Veggies/Chicken",280 kcal,"[""Soak raw rice for 4-5 hours. Grind with grated coconut and cooked rice/poha to a smooth batter."", ""Add yeast and sugar to warm water, let it froth, then mix into batter. Ferment for 8 hours."", ""Add salt and coconut milk to thin the batter."", ""Heat an Appam pan (curved). Pour a ladle of batter and swirl the pan to coat the sides."", ""Cover and cook until edges are crisp and center is soft."", ""Stew: Sauté whole spices, ginger, garlic, and onions. Add veggies (carrot, potato, peas) and thin coconut milk. Boil."", ""Once veggies are cooked, add thick coconut milk and turn off heat immediately.""]"
Kerala,Puttu and Kadala Curry,https://www.google.com/search?tbm=isch&q=Puttu+Kadala,40 mins,"Rice Flour; Coconut; Black Chickpeas; Spices",300 kcal,"[""Mix rice flour with salt and sprinkle water gradually. Rub with fingers until it resembles moist breadcrumbs (puttu texture)."", ""In a Puttu maker (cylindrical steamer), layer grated coconut, then rice flour mixture, then coconut again."", ""Steam for 5-10 minutes."", ""Kadala Curry: Soak black chickpeas overnight and pressure cook."", ""Roast coconut, coriander seeds, and dry chilies; grind to a paste."", ""Sauté onions and spices. Add chickpeas and the ground paste. Simmer until thick.""]"
Kerala,Karimeen Pollichathu,https://www.google.com/search?tbm=isch&q=Karimeen+Pollichathu,50 mins,"Pearl Spot Fish; Banana Leaves; Onion; Tomato; Spices",350 kcal,"[""Clean the Karimeen (Pearl Spot) fish and make gashes on it."", ""Marinate with red chili, turmeric, pepper, and lemon juice. Shallow fry lightly."", ""Sauté onions, ginger, garlic, tomatoes, and curry leaves to make a thick masala."", ""Take a banana leaf, wilt it over flame (to make it flexible)."", ""Place some masala on the leaf, place the fried fish, and cover with more masala."", ""Wrap the leaf into a packet and tie with fiber."", ""Roast the packet on a tawa with coconut oil until the leaf chars.""]"
Kerala,Malabar Parotta,https://www.google.com/search?tbm=isch&q=Malabar+Parotta,60 mins,"Maida (Refined Flour); Egg; Oil/Ghee; Water",400 kcal,"[""Mix Maida (refined flour), sugar, salt, egg (optional), and water. Knead into a soft dough."", ""Rest the dough for at least 2 hours."", ""Divide into balls. Roll out paper-thin on an oiled surface."", ""Gather the dough sheet into pleats (like a paper fan) to create layers."", ""Coil the pleated dough into a spiral."", ""Roll flat again gently."", ""Cook on a hot tawa with plenty of oil/ghee until golden and flaky."", ""Crush the hot parotta between your hands to separate the layers.""]"
Kerala,Avial,https://www.google.com/search?tbm=isch&q=Kerala+Avial,30 mins,"Mixed Vegetables (Yam; Drumstick; Carrot; etc.); Coconut; Curd; Coconut Oil",200 kcal,"[""Cut mixed vegetables (yam, drumstick, raw banana, carrot, beans, pumpkin) into long baton strips."", ""Boil vegetables with turmeric, salt, and a little water until tender."", ""Grind fresh coconut, green chilies, and cumin seeds into a coarse paste."", ""Add the coconut paste to the cooked vegetables and mix gently."", ""Cook for 2 minutes."", ""Remove from heat. Add beaten curd (yogurt) and mix."", ""Drizzle raw coconut oil and fresh curry leaves on top.""]"
Madhya Pradesh,Poha,https://www.google.com/search?tbm=isch&q=Indori+Poha,15 mins,"Flattened Rice; Fennel Seeds; Onions; Sev; Pomegranate",200 kcal,"[""Wash thick Poha (flattened rice) gently and drain water. Sprinkle salt and sugar, mix, and set aside."", ""Heat oil. Sauté mustard seeds, peanuts, and finely chopped onions."", ""Add green chilies and turmeric."", ""Add the softened Poha and steam it covered on very low heat for 5 minutes."", ""Turn off heat."", ""Top with Jeeravan masala (special spice mix), Sev, chopped onions, coriander, and pomegranate seeds."", ""Serve with a lemon wedge.""]"
Madhya Pradesh,Dal Bafla,https://www.google.com/search?tbm=isch&q=Dal+Bafla,60 mins,"Wheat Flour; Maize Flour; Ghee; Mixed Dal",450 kcal,"[""Dough: Mix wheat flour, maize flour (makka), ghee, yogurt, and salt. Knead a stiff dough."", ""Make round balls (Baflas)."", ""Boil water with turmeric. Drop Baflas in boiling water and cook until they float."", ""Drain and dry. Bake them in an oven or Tandoor until the crust is hard and brown."", ""Crush slightly and dip in a bowl of melted Ghee."", ""Serve with spicy Dal (lentil curry) and Laddu.""]"
Madhya Pradesh,Bhutte Ka Kees,https://www.google.com/search?tbm=isch&q=Bhutte+Ka+Kees,30 mins,"Grated Corn; Milk; Mustard Seeds; Coconut; Spices",250 kcal,"[""Grate fresh corn cobs (sweet corn or desi corn)."", ""Heat ghee in a pan. Add mustard seeds, cumin, and asafoetida (hing)."", ""Add grated ginger and green chilies."", ""Add the grated corn and sauté for 10-15 minutes until roasted."", ""Add milk (about 1 cup) to the corn."", ""Simmer until the mixture thickens and absorbs the milk."", ""Add salt, red chili, and a little sugar."", ""Garnish with grated coconut and coriander.""]"
Madhya Pradesh,Bhopali Gosht Korma,https://www.google.com/search?tbm=isch&q=Bhopali+Gosht+Korma,60 mins,"Mutton; Yogurt; Spices; Coriander Seeds; Onions",400 kcal,"[""Wash mutton pieces."", ""Heat oil/ghee. Fry thinly sliced onions until crisp brown (Birista). Crush them."", ""In the same oil, add whole spices and mutton. Sear the meat."", ""Add ginger-garlic paste, coriander powder, and red chili powder."", ""Add beaten yogurt and the crushed fried onions."", ""Cook on high heat until oil separates."", ""Add water, cover, and slow cook (or pressure cook) until mutton is meltingly soft."", ""The gravy should be silky and aromatic.""]"
Madhya Pradesh,Mawa Bati,https://www.google.com/search?tbm=isch&q=Mawa+Bati,45 mins,"Mawa (Khoya); Arrowroot powder; Dry Fruits; Sugar Syrup",400 kcal,"[""Knead crumbled Khoya (Mawa) with a little arrowroot powder or refined flour to make a soft dough."", ""Stuffing: Mix chopped nuts (cashews, almonds) with cardamom powder."", ""Make small balls of Mawa dough and stuff the nut mixture inside."", ""Deep fry in ghee on very low heat until dark golden brown."", ""Prepare a sticky sugar syrup (chashni)."", ""Soak the fried balls in warm syrup for an hour."", ""Serve warm or cold.""]"
Maharashtra,Vada Pav,https://www.google.com/search?tbm=isch&q=Vada+Pav,40 mins,"Potatoes; Gram Flour; Pav Bun; Garlic Chutney",300 kcal,"[""Boil and mash potatoes."", ""Heat little oil, temper mustard seeds, curry leaves, and green chilies. Add turmeric."", ""Mix this tempering with mashed potatoes, salt, and coriander. Make balls."", ""Batter: Mix besan (gram flour), salt, turmeric, and soda with water."", ""Dip potato balls in batter and deep fry."", ""Chutney: Grind roasted peanuts, garlic, and red chili powder (dry chutney)."", ""Slice a Pav bun. Apply chutney. Place the Vada inside.""]"
Maharashtra,Misal Pav,https://www.google.com/search?tbm=isch&q=Misal+Pav,45 mins,"Sprouted Moth Beans; Farsan (Crunchy mix); Onions; Pav",450 kcal,"[""Soak Moth beans (Matki) and sprout them."", ""Cook sprouts with turmeric and salt."", ""Paste: Roast onion, coconut, ginger, garlic, and spices. Grind to paste."", ""Heat oil (generously). Fry the paste until oil releases."", ""Add Goda Masala (Maharashtrian spice mix) and red chili powder."", ""Add water and cooked sprouts. Boil to make a thin, spicy gravy (Kat/Rassa)."", ""Serve: In a bowl, add sprouts, top with Farsan (crunchy mix), chopped onion, and coriander."", ""Pour the spicy gravy on top. Serve with Pav.""]"
Maharashtra,Puran Poli,https://www.google.com/search?tbm=isch&q=Puran+Poli,60 mins,"Chana Dal; Jaggery; Wheat Flour; Cardamom; Ghee",350 kcal,"[""Boil Chana Dal until soft but not mushy. Drain water (use water for Katachi Amti)."", ""Cook the dal with Jaggery in a pan until it becomes a thick, dry paste (Puran)."", ""Add cardamom and nutmeg powder. Grind/mash smoothly."", ""Dough: Knead wheat flour and maida with water and oil."", ""Take a ball of dough, flatten, stuff a large portion of Puran, and seal."", ""Dust flour and roll into a thin roti."", ""Cook on a tawa with plenty of Ghee on both sides.""]"
Maharashtra,Pav Bhaji,https://www.google.com/search?tbm=isch&q=Pav+Bhaji,40 mins,"Mixed Vegetables; Butter; Pav Bhaji Masala; Pav",400 kcal,"[""Boil potatoes, cauliflower, peas, and carrots. Mash them completely."", ""Heat butter on a large tawa."", ""Sauté onions, capsicum (bell pepper), and tomatoes."", ""Add ginger-garlic paste and Pav Bhaji Masala."", ""Add the mashed vegetables and water."", ""Mash everything together on the tawa while cooking until it's a smooth, thick gravy."", ""Add a big dollop of butter and coriander."", ""Roast Pav buns with butter. Serve hot.""]"
Maharashtra,Modak,https://www.google.com/search?tbm=isch&q=Ukadiche+Modak,50 mins,"Rice Flour; Coconut; Jaggery; Cardamom",250 kcal,"[""Filling: Cook fresh grated coconut and jaggery together until moist and sticky. Add cardamom."", ""Shell: Boil water with ghee and salt. Add rice flour, mix, cover, and switch off heat. Let it steam."", ""Knead the warm rice flour dough until smooth."", ""Take a small ball, flatten it into a cup shape with thin edges."", ""Place filling in center. Pinch the edges to make pleats."", ""Bring pleats together to seal the top."", ""Steam for 10-15 minutes.""]"
Manipur,Kangshoi,https://www.google.com/search?tbm=isch&q=Kangshoi,25 mins,"Seasonal Veggies; Dry Fish; Water; Onion",100 kcal,"[""Boil water in a pot."", ""Add washed chunks of seasonal vegetables (potato, cabbage, spinach, peas)."", ""Add fried fish pieces or dried fish (Ngari) for flavor."", ""Add sliced onions, ginger slices, and salt."", ""Cover and boil until vegetables are tender."", ""Add fresh herbs (Manipuri coriander) and green chilies."", ""Serve as a healthy, oil-free stew.""]"
Manipur,Eromba,https://www.google.com/search?tbm=isch&q=Eromba,20 mins,"Boiled Vegetables; Fermented Fish (Ngari); King Chili",150 kcal,"[""Boil vegetables (potatoes, bamboo shoots, beans) until very soft."", ""Roast Fermented Fish (Ngari) over a flame."", ""Roast King Chili (Ghost Pepper) and red chilies."", ""Mash the chilies, Ngari, and salt together to a paste."", ""Mash the boiled vegetables (keep them slightly chunky, not puree)."", ""Mix the chili-fish paste with the vegetables."", ""Garnish with chopped onions and coriander.""]"
Manipur,Chak-Hao Kheer,https://www.google.com/search?tbm=isch&q=Chak+Hao+Kheer,50 mins,"Black Rice; Milk; Sugar; Cardamom; Dry Fruits",300 kcal,"[""Wash the black rice (Chak-Hao). Soak for 2 hours."", ""Boil milk in a heavy bottom pan."", ""Add the soaked rice."", ""Simmer on low heat, stirring occasionally, until the rice is cooked and milk turns purple."", ""Add sugar and cardamom powder."", ""Cook until creamy."", ""Garnish with nuts and serve chilled or warm.""]"
Manipur,Singju,https://www.google.com/search?tbm=isch&q=Singju+Salad,20 mins,"Lotus Root; Cabbage; Herbs; Perilla Seeds; Chili",120 kcal,"[""Finely chop cabbage, lotus stem, long beans, banana flower, and herbs."", ""Roast Perilla seeds (Thoiding) and grind to powder."", ""Roast chickpea flour (Besan) slightly."", ""Roast dried red chilies and crush them."", ""In a large bowl, mix the chopped vegetables with fermented fish sauce (or salt for veg version)."", ""Add the roasted powders and chili flakes."", ""Toss well like a salad.""]"
Manipur,Nga Thongba,https://www.google.com/search?tbm=isch&q=Nga+Thongba,40 mins,"Fish; Potatoes; Turmeric; Herbs (Ooti)",250 kcal,"[""Cut fish into pieces. Rub with turmeric and salt."", ""Heat oil. Sauté onion and chives (Maroi)."", ""Add crushed ginger and garlic."", ""Add potatoes cut into cubes."", ""Add turmeric, chili powder, and cumin."", ""Add water and bring to boil."", ""Add fish pieces and simmer until cooked."", ""Garnish with fresh herbs.""]"
Meghalaya,Jadoh,https://www.google.com/search?tbm=isch&q=Jadoh,45 mins,"Red Rice; Pork/Chicken; Onions; Ginger; Black Pepper",400 kcal,"[""Cut pork into small cubes."", ""Heat oil. Sauté onions, ginger paste, and turmeric."", ""Add pork pieces and fry until browned."", ""Add washed short-grain rice (Joha rice or red rice)."", ""Fry rice with meat for 2 minutes."", ""Add salt and black pepper powder."", ""Add water (2:1 ratio). Cover and cook until rice is done and water is absorbed.""]"
Meghalaya,Doh Khleh,https://www.google.com/search?tbm=isch&q=Doh+Khleh,30 mins,"Pork; Onions; Ginger; Chillies; Salt",300 kcal,"[""Boil pork pieces with salt until completely soft."", ""Drain water (keep stock for soup)."", ""Chop the pork fat and meat into very small pieces or mince it."", ""Finely chop raw onions and ginger."", ""Chop green chilies."", ""Mix the meat, onions, ginger, and chilies in a bowl."", ""Season with salt. Serve at room temperature.""]"
Meghalaya,Nakham Bitchi,https://www.google.com/search?tbm=isch&q=Nakham+Bitchi,20 mins,"Dry Fish; Vegetables; Soda; Chilies",100 kcal,"[""Take Dry Fish (Nakham). Fry it over a flame or in a pan dry."", ""Boil water in a pot."", ""Add chopped vegetables (pumpkin, beans, etc.)."", ""Add the fried dry fish."", ""Add a pinch of cooking soda (khar)."", ""Add plenty of green chilies."", ""Simmer until veggies are soft. Mash slightly. Serve as a soup.""]"
Meghalaya,Pumaloi,https://www.google.com/search?tbm=isch&q=Pumaloi,40 mins,"Powdered Rice; Water; Coconut (optional)",200 kcal,"[""Soak special Pumaloi rice (or red rice) overnight."", ""Drain and dry the rice, then pound it into a powder."", ""Mix rice powder with water to make a crumbly texture."", ""Place in a specialized earthen steamer pot (Khiew Ranei)."", ""Steam over boiling water for 30-40 minutes."", ""Serve with Tungrymbai or meat curry.""]"
Meghalaya,Tungrymbai,https://www.google.com/search?tbm=isch&q=Tungrymbai,45 mins,"Fermented Soybeans; Pork fat; Sesame seeds; Ginger",350 kcal,"[""Mash fermented soy beans."", ""Boil pork fat pieces in water until soft."", ""Add the mashed beans to the pot."", ""Add ginger paste, turmeric, and black sesame seed paste."", ""Simmer on very low heat for 1-2 hours."", ""Stir occasionally to prevent sticking."", ""The mixture becomes a thick, savory paste.""]"
Mizoram,Sanpiau,https://www.google.com/search?tbm=isch&q=Sanpiau,30 mins,"Rice Porridge; Fish Sauce; Coriander; Spring Onions",250 kcal,"[""Cook rice with extra water to make a thick porridge."", ""Prepare sauce: Mix fish sauce, water, and pulverized rice powder."", ""Fry finely sliced onions until crisp."", ""Mix the sauce into the hot rice porridge."", ""Top with crisp onions, fresh coriander, crushed black pepper, and spring onions.""]"
Mizoram,Vawksa Rep,https://www.google.com/search?tbm=isch&q=Vawksa+Rep,40 mins,"Smoked Pork; Chilies; Local Herbs; Leafy Greens",350 kcal,"[""Cut Smoked Pork into cubes."", ""Wash and cut mustard leaves and spinach."", ""Heat a pan. Add pork and fry (it releases its own fat)."", ""Add chopped green chilies and salt."", ""Add the leafy greens and toss."", ""Add a splash of water, cover, and cook until pork is tender and water dries up.""]"
Mizoram,Bai,https://www.google.com/search?tbm=isch&q=Mizo+Bai,25 mins,"Vegetables; Pork Sauce (Sa-um); Spinach; Bamboo Shoot",150 kcal,"[""Boil water in a pot."", ""Add 'Sa-um' (fermented pork fat) for flavor."", ""Add chopped vegetables like beans, brinjal, potato, and bamboo shoots."", ""Add sodium bicarbonate (soda)."", ""Add green chilies."", ""Cook until vegetables are mushy and soup is thick."", ""Add cooked rice to thicken if needed.""]"
Mizoram,Koat Pitha,https://www.google.com/search?tbm=isch&q=Koat+Pitha,30 mins,"Rice Flour; Banana; Jaggery; Oil",250 kcal,"[""Soak rice and grind to a coarse powder."", ""Mash ripe bananas."", ""Mix rice powder, mashed bananas, and jaggery."", ""Add a little water to make a thick batter."", ""Heat oil."", ""Drop spoonfuls of batter into hot oil."", ""Deep fry until dark brown and crispy outside.""]"
Mizoram,Panch Phoron Tarka,https://www.google.com/search?tbm=isch&q=Panch+Phoron+Tarka+Mizoram,30 mins,"Pumpkin; Potatoes; Panch Phoron Spice; Dry Chili",200 kcal,"[""Cut pumpkin and potatoes into cubes."", ""Heat oil."", ""Add Panch Phoron (5 spice mix: cumin, mustard, fennel, fenugreek, nigella)."", ""Add dry red chilies."", ""Add the vegetables and turmeric."", ""Stir fry until cooked (dry dish)."", ""Season with salt.""]"
Nagaland,Smoked Pork with Bamboo Shoot,https://www.google.com/search?tbm=isch&q=Smoked+Pork+Bamboo+Shoot,60 mins,"Smoked Pork; Fermented Bamboo Shoot; Raja Mircha",450 kcal,"[""Wash the Smoked Pork thoroughly with warm water to remove ash/dirt."", ""Cut into bite-sized pieces."", ""Put pork in a pot with water. Add crushed ginger and garlic."", ""Add King Chili (Raja Mircha) - be careful, it's hot."", ""Add fermented bamboo shoots."", ""Cover and cook on medium heat for 45 minutes."", ""The gravy should be semi-dry and thick.""]"
Nagaland,Axone (Akhuni),https://www.google.com/search?tbm=isch&q=Axone+Curry,45 mins,"Fermented Soybeans (Axone); Smoked Pork/Beef; Chilies; Ginger",400 kcal,"[""Take fermented soybean cakes (Axone). Wrap in banana leaf and roast slightly (optional)."", ""Crush the Axone."", ""Put smoked meat (pork or beef) in a pot with water."", ""Add crushed ginger, garlic, and plenty of chilies."", ""Add the crushed Axone."", ""Simmer until the meat is cooked and the liquid forms a thick, pungent gravy.""]"
Nagaland,Galho,https://www.google.com/search?tbm=isch&q=Galho+Nagaland,35 mins,"Rice; Vegetables; Smoked Meat; Axone (optional)",300 kcal,"[""Wash rice and mix with lentils (optional)."", ""Put rice in a pot with water."", ""Add chopped seasonal vegetables and wild leaves."", ""Add smoked meat pieces."", ""Add a spoonful of Axone (fermented soy) for flavor."", ""Cook until rice is mushy (like Khichdi)."", ""Garnish with ginger shards.""]"
Nagaland,Hinkejvu,https://www.google.com/search?tbm=isch&q=Hinkejvu,25 mins,"Colocasia; Cabbage; Mustard Leaves; French Beans",120 kcal,"[""Wash colocasia leaves, mustard leaves, beans, and cabbage."", ""Boil water in a pot."", ""Add all the vegetables."", ""Add salt."", ""Do not add oil or spices."", ""Cook until vegetables are completely soft and water is mostly evaporated."", ""Mash lightly.""]"
Nagaland,Rosep Aon,https://www.google.com/search?tbm=isch&q=Rosep+Aon,30 mins,"Mixed Vegetables; Dry Fish; Sichuan Pepper",150 kcal,"[""Boil mixed vegetables (beans, brinjal, bitter gourd)."", ""Roast dry fish and shred it."", ""Mix boiled veggies and dry fish."", ""Add crushed Naga pepper (Sichuan pepper) and chilies."", ""Add salt and local herbs."", ""Mix well. It's a dry side dish.""]"
Odisha,Dalma,https://www.google.com/search?tbm=isch&q=Dalma+Recipe,45 mins,"Toor Dal; Pumpkin; Raw Banana; Brinjal; Panch Phoron",220 kcal,"[""Soat Toor Dal."", ""Cut pumpkin, raw banana, brinjal, potato, and drumstick into large chunks."", ""Boil dal and vegetables together with turmeric and salt until soft."", ""Tempering: Heat ghee/oil. Add Panch Phoron (5 spices) and dry red chilies."", ""Add grated coconut (optional)."", ""Pour the tempering over the boiled dal-vegetable mix."", ""Simmer for 2 minutes.""]"
Odisha,Chhena Poda,https://www.google.com/search?tbm=isch&q=Chhena+Poda,90 mins,"Fresh Chhena (Cottage Cheese); Sugar; Cardamom; Sal Leaves",300 kcal,"[""Take fresh Chhena (soft cottage cheese). Crumble it well."", ""Add sugar and mix until it feels light."", ""Add cardamom powder and a little semolina (suji) for binding."", ""Add raisins and cashews."", ""Grease a cake tin and line it with Sal leaves or banana leaves (for authentic aroma)."", ""Pour the mixture in."", ""Bake in an oven or pressure cooker (without whistle) for 45-60 mins until the top is dark brown/burnt look.""]"
Odisha,Pakhala Bhata,https://www.google.com/search?tbm=isch&q=Pakhala+Bhata,10 mins,"Cooked Rice; Water; Curd; Green Chili; Mustard Seeds",150 kcal,"[""Cook rice. Let it cool slightly."", ""Add water to the rice and let it ferment overnight (for 8-10 hours). This is 'Basi Pakhala'."", ""Next day, add curd to the rice water mix."", ""Add salt."", ""Tempering: Heat oil, add mustard seeds, curry leaves, and dry red chilies."", ""Pour tempering into the rice bowl."", ""Serve with fried fish or bharta.""]"
Odisha,Macha Ghanta,https://www.google.com/search?tbm=isch&q=Macha+Ghanta,60 mins,"Fish Head; Chana Dal; Potatoes; Onions; Spices",350 kcal,"[""Clean and fry the Fish Head (Rohu/Katla). Break it into pieces."", ""Soak and boil Chana Dal and cubed potatoes/pumpkin."", ""Heat oil. Sauté onions, ginger-garlic paste, and tomatoes."", ""Add turmeric, chili powder, coriander powder, and Garam Masala."", ""Add the fried fish head pieces and coat with masala."", ""Add the boiled dal and vegetables."", ""Simmer until everything blends together into a thick curry.""]"
Odisha,Chungdi Malai,https://www.google.com/search?tbm=isch&q=Chungdi+Malai,40 mins,"Prawns; Coconut Milk; Ginger-Garlic; Spices",320 kcal,"[""Marinate prawns with turmeric and salt. Lightly fry them."", ""Grind onion, ginger, and garlic to paste."", ""Extract thick coconut milk."", ""Heat oil. Add whole spices (cardamom, cinnamon)."", ""Fry the onion paste until golden."", ""Add spices (chili, cumin powder)."", ""Add the coconut milk and bring to boil."", ""Add prawns and simmer gently for 5 minutes."", ""Finish with a little sugar and garam masala.""]"
Punjab,Butter Chicken,https://www.google.com/search?tbm=isch&q=Butter+Chicken,50 mins,"Chicken; Tomatoes; Butter; Cream; Cashews; Fenugreek",450 kcal,"[""Marinate chicken with yogurt, lemon juice, ginger-garlic paste, red chili powder, and salt for 1 hour."", ""Grill or pan-fry the chicken until cooked."", ""Heat butter in a pan. Add whole spices and ginger-garlic paste."", ""Add tomato puree and cook until oil separates."", ""Add cashew nut paste, red chili powder, sugar, and salt."", ""Add the cooked chicken pieces."", ""Stir in fresh cream and crushed Kasuri Methi (dried fenugreek leaves)."", ""Simmer for 5 minutes and serve.""]"
Punjab,Sarson Da Saag & Makki Roti,https://www.google.com/search?tbm=isch&q=Sarson+Da+Saag,90 mins,"Mustard Greens; Spinach; Maize Flour; Ghee",400 kcal,"[""Wash mustard greens (sarson), spinach (palak), and bathua. Chop coarsely."", ""Pressure cook greens with ginger, garlic, and green chilies until soft."", ""Mash the greens using a wooden churner (madhani) or blender. Add maize flour to thicken."", ""Cook the mashed greens with ghee and spices for 20 minutes."", ""Roti: Knead maize flour (makki atta) with warm water."", ""Pat the dough into thick flatbreads."", ""Cook on a tawa with ghee until brown spots appear."", ""Serve with white butter/jaggery.""]"
Punjab,Chole Bhature,https://www.google.com/search?tbm=isch&q=Chole+Bhature,60 mins,"Chickpeas; Maida; Spices; Tea bags (for color)",550 kcal,"[""Soak chickpeas overnight. Pressure cook with tea bags (for dark color) and whole spices."", ""Heat oil. Sauté onion paste and ginger-garlic paste."", ""Add tomato puree, chole masala, coriander powder, and chili powder."", ""Add the boiled chickpeas and simmer."", ""Bhature: Knead maida (flour) with yogurt, baking powder, sugar, and salt. Ferment for 2 hours."", ""Roll into ovals and deep fry in hot oil until they puff up.""]"
Punjab,Amritsari Kulcha,https://www.google.com/search?tbm=isch&q=Amritsari+Kulcha,45 mins,"Refined Flour; Potato filling; Coriander Seeds; Butter",350 kcal,"[""Make a dough with maida, yogurt, baking powder, and soda. Let it rest."", ""Filling: Mash boiled potatoes with onions, green chilies, anardana (pomegranate seeds), and spices."", ""Stuff a ball of dough with the potato mix."", ""Roll it out gently."", ""Apply water on one side and stick it onto a hot tawa (or bake in tandoor)."", ""Invert the tawa over flame to roast the top side."", ""Crush the kulcha with hands to flake it and top with a chunk of butter.""]"
Punjab,Dal Makhani,https://www.google.com/search?tbm=isch&q=Dal+Makhani,8 hours,"Whole Black Urad; Kidney Beans; Butter; Cream",400 kcal,"[""Soat whole black urad and kidney beans (rajma) overnight."", ""Pressure cook with salt and water until very soft."", ""Heat butter. Add ginger-garlic paste and tomato puree."", ""Add red chili powder and cook until butter separates."", ""Add the boiled dal and mash slightly against the pot sides."", ""Add plenty of cream and butter."", ""Simmer on very low heat for 1-2 hours for creaminess.""]"
Rajasthan,Dal Baati Churma,https://www.google.com/search?tbm=isch&q=Dal+Baati+Churma,90 mins,"Wheat Flour; Mixed Lentils; Ghee; Semolina",600 kcal,"[""Baati: Knead coarse wheat flour with ghee, rava, and salt. Make hard balls. Bake in oven/tandoor until brown and cracked. Dip in ghee."", ""Dal: Cook mix of 5 lentils (toor, chana, moong, masoor, urad). Temper with ghee, cloves, mustard, and red chilies."", ""Churma: Take some baked Baatis. Crush them into powder. Mix with melted ghee and powdered sugar/jaggery."", ""Serve all three together.""]"
Rajasthan,Laal Maas,https://www.google.com/search?tbm=isch&q=Laal+Maas,60 mins,"Mutton; Mathania Red Chilies; Yogurt; Garlic",450 kcal,"[""Soat Mathania red chilies (mild but red) and grind to a fine paste."", ""Heat mustard oil (or ghee). Sauté whole spices and onions."", ""Add mutton pieces and sear."", ""Add the red chili paste, garlic paste, and yogurt."", ""Cook on high flame until oil separates."", ""Add water and slow cook until the meat falls off the bone. The gravy should be bright red.""]"
Rajasthan,Gatte Ki Sabzi,https://www.google.com/search?tbm=isch&q=Gatte+Ki+Sabzi,40 mins,"Gram Flour (Besan); Curd; Spices",300 kcal,"[""Mix besan (gram flour) with yogurt, oil, carom seeds, and spices. Knead stiff dough."", ""Roll dough into long cylinders."", ""Boil these rolls in water until they float. Drain and cut into discs (Gatte)."", ""Gravy: Whisk yogurt with turmeric, chili, and coriander powder."", ""Heat oil, add cumin, and pour the yogurt mix. Stir continuously to boil."", ""Add the Gatte pieces and simmer.""]"
Rajasthan,Ker Sangri,https://www.google.com/search?tbm=isch&q=Ker+Sangri,30 mins,"Dried Ker Berries; Sangri Beans; Spices; Oil",250 kcal,"[""Soat dried Ker berries and Sangri beans overnight in water."", ""Boil them until tender. Drain."", ""Heat generous amount of oil. Add cumin and dry red chilies."", ""Add turmeric, coriander, and amchur (mango powder)."", ""Add the boiled Ker and Sangri."", ""Cook for 5-7 minutes. This dish can be stored for days.""]"
Rajasthan,Ghevar,https://www.google.com/search?tbm=isch&q=Ghevar,60 mins,"Flour; Ghee; Ice cubes; Sugar Syrup; Rabdi",450 kcal,"[""Rub ghee and ice cubes together in a bowl until ghee becomes white and creamy."", ""Add flour and milk alternately to make a thin pouring batter."", ""Heat ghee in a deep vessel."", ""Pour batter in a thin stream into the center of hot ghee."", ""Wait for bubbles to settle, then pour more. Repeat to build layers."", ""Fry until honeycomb structure forms and turns golden."", ""Remove and dip in sugar syrup. Top with Rabdi and nuts.""]"
Sikkim,Momo,https://www.google.com/search?tbm=isch&q=Sikkim+Momo,40 mins,"Flour; Minced Meat/Vegetable; Onion; Garlic",200 kcal,"[""Dough: Mix flour and water. Knead well."", ""Filling: Mix minced meat (or finely chopped veggies) with onion, garlic, ginger, soy sauce, and salt."", ""Roll small circles of dough."", ""Place filling in center. Pleat the edges to seal into a crescent or round shape."", ""Steam in a steamer for 10-15 minutes."", ""Serve with spicy tomato-chili chutney.""]"
Sikkim,Thukpa,https://www.google.com/search?tbm=isch&q=Sikkim+Thukpa,30 mins,"Noodle; Vegetable/Meat Broth; Garlic; Soy Sauce",300 kcal,"[""Boil noodles and keep aside."", ""Heat oil. Sauté garlic, ginger, onion, and chilies."", ""Add chopped vegetables (carrot, cabbage, spinach) and meat."", ""Add vegetable/chicken stock or water."", ""Add soy sauce, salt, and pepper. Boil for 10 minutes."", ""Add the cooked noodles just before serving."", ""Garnish with spring onions.""]"
Sikkim,Phagshapa,https://www.google.com/search?tbm=isch&q=Phagshapa,45 mins,"Pork Fat strips; Radish; Dried Chilies",400 kcal,"[""Cut pork belly (with fat) into strips."", ""Heat a pan (no oil needed if fatty pork). Stir fry pork until brown."", ""Add sliced onions and radishes."", ""Add dried red chilies (whole) and ginger."", ""Add a little water and cover."", ""Stew until the radish is soft and pork is tender."", ""The dish should be slightly tangy and spicy.""]"
Sikkim,Sha Phaley,https://www.google.com/search?tbm=isch&q=Sha+Phaley,40 mins,"Dough; Minced Beef/Chicken; Cabbage; Onion",350 kcal,"[""Make a dough with flour and water."", ""Mix minced beef/chicken with cabbage, onion, ginger, and spices."", ""Roll dough into circles."", ""Place filling on one side, fold over to make a semi-circle."", ""Crimp the edges to seal."", ""Deep fry in hot oil until golden brown and crispy."", ""Serve with soup or chutney.""]"
Sikkim,Gundruk,https://www.google.com/search?tbm=isch&q=Gundruk+Soup,20 mins,"Fermented Leafy Greens; Tomato; Garlic",100 kcal,"[""Soat Gundruk (fermented leafy greens) in water for 10 minutes."", ""Heat oil. Fry chopped onions and tomatoes."", ""Add turmeric and salt."", ""Add the soaked Gundruk and fry."", ""Add water to make a soup."", ""Simmer for 10 minutes. Serve with rice.""]"
Tamil Nadu,Idli Sambar,https://www.google.com/search?tbm=isch&q=Idli+Sambar,40 mins,"Rice-Urad Batter; Toor Dal; Veggies; Tamarind",200 kcal,"[""Soat rice and urad dal separately. Grind to batter and ferment overnight."", ""Grease Idli molds. Pour batter. Steam for 10-12 minutes."", ""Sambar: Boil toor dal with turmeric."", ""Cook vegetables (drumstick, pumpkin, carrot) in tamarind water."", ""Add boiled dal and Sambar powder to veggies."", ""Temper with mustard seeds, curry leaves, and dry chilies.""]"
Tamil Nadu,Chettinad Chicken,https://www.google.com/search?tbm=isch&q=Chettinad+Chicken,50 mins,"Chicken; Roasted Spices (Pepper; Fennel); Coconut; Curry Leaves",350 kcal,"[""Dry roast coriander, cumin, fennel, pepper, cinnamon, cloves, and dry chilies. Grind to powder."", ""Marinate chicken with turmeric and yogurt."", ""Heat oil. Sauté onions, curry leaves, and ginger-garlic paste."", ""Add tomatoes and cook until soft."", ""Add the ground Chettinad masala."", ""Add chicken and cover with water."", ""Simmer until gravy is thick and aromatic.""]"
Tamil Nadu,Pongal,https://www.google.com/search?tbm=isch&q=Ven+Pongal,30 mins,"Rice; Moong Dal; Black Pepper; Cumin; Ghee; Cashews",300 kcal,"[""Dry roast moong dal until fragrant."", ""Pressure cook rice and moong dal together with plenty of water until mushy."", ""Add salt and mash the mixture lightly."", ""Heat ample ghee/oil."", ""Add black pepper, cumin seeds, ginger, curry leaves, and cashew nuts."", ""Pour this tempering over the mashed rice-dal mix."", ""Mix well and serve hot with chutney.""]"
Tamil Nadu,Chicken 65,https://www.google.com/search?tbm=isch&q=Chicken+65,30 mins,"Chicken cubes; Cornflour; Curd; Red Chili; Curry Leaves",350 kcal,"[""Cut chicken into bite-sized cubes."", ""Marinate with ginger-garlic paste, red chili powder, turmeric, cornflour, rice flour, egg (optional), curd, and salt."", ""Let it sit for 30 minutes."", ""Deep fry in hot oil until crispy."", ""In a separate pan, heat little oil."", ""Toss slit green chilies and curry leaves."", ""Add the fried chicken and toss well.""]"
Tamil Nadu,Paniyaram,https://www.google.com/search?tbm=isch&q=Kuzhi+Paniyaram,20 mins,"Leftover Idli Batter; Onions; Green Chili; Mustard Seeds",180 kcal,"[""Take leftover Idli/Dosa batter."", ""Heat oil. Sauté mustard seeds, udad dal, finely chopped onions, green chilies, and curry leaves."", ""Mix this sautéed mix into the batter."", ""Heat a Paniyaram pan (mold pan). Add a drop of oil in each cavity."", ""Pour batter into cavities."", ""Cover and cook. Flip when bottom is golden."", ""Cook other side. Serve with chutney.""]"
Telangana,Hyderabadi Haleem,https://www.google.com/search?tbm=isch&q=Hyderabadi+Haleem,4 hours,"Mutton; Broken Wheat; Lentils; Ghee; Spices",500 kcal,"1. Slow cook meat and wheat for hours. 2. Mash continuously until pasty and elastic. 3. Top with fried onions and ghee."
Telangana,Sarva Pindi,https://www.google.com/search?tbm=isch&q=Sarva+Pindi,30 mins,"Rice Flour; Chana Dal; Peanuts; Sesame; Chili",250 kcal,"1. Knead dough with ingredients. 2. Press flat on pan. 3. Make holes; add oil; and roast until crisp."
Telangana,Pacchi Pulusu,https://www.google.com/search?tbm=isch&q=Pacchi+Pulusu,15 mins,"Tamarind water; Onions; Jaggery; Green Chili; Roasted Brinjal (opt)",100 kcal,"1. Extract raw tamarind juice. 2. Add jaggery; onions and salt. 3. Temper with charcoal burnt chili/garlic (No cooking needed)."
Telangana,Golichina Mamsam,https://www.google.com/search?tbm=isch&q=Golichina+Mamsam,45 mins,"Mutton; Onions; Ginger-Garlic; Spices",400 kcal,"1. Boil mutton. 2. Fry (Golichina) in oil with spices until dry and roasted dark brown."
Telangana,Sakinalu,https://www.google.com/search?tbm=isch&q=Sakinalu,45 mins,"Rice Flour; Sesame Seeds; Carom Seeds (Ajwain)",300 kcal,"1. Make dough. 2. Hand-roll into concentric circles. 3. Deep fry. (Famous Makar Sankranti snack)."
Tripura,Mui Borok,https://www.google.com/search?tbm=isch&q=Mui+Borok,40 mins,"Berma (Fermented Fish); Veggies; Rice",150 kcal,"1. The essence of Tripura cuisine. Cook veggies and fish paste without oil. Healthy and organic."
Tripura,Kosoi Bwtwi,https://www.google.com/search?tbm=isch&q=Kosoi+Bwtwi,25 mins,"Beans; Garlic; Ginger; Green Chilies; Berma",120 kcal,"1. Boil beans and tofu (optional). 2. Add crushed garlic and fermented fish. 3. Serve as a semi-dry dish."
Tripura,Gudok,https://www.google.com/search?tbm=isch&q=Gudok+Tripura,30 mins,"Berma; Potatoes; Jackfruit seeds; Bamboo shoot",180 kcal,"1. Mash boiled vegetables. 2. Mix with fermented fish paste and chilies. 3. Cook in bamboo pipes (traditional) or pot."
Tripura,Wahan Mosdeng,https://www.google.com/search?tbm=isch&q=Wahan+Mosdeng,35 mins,"Pork; Onion; Coriander; Green Chili",350 kcal,"1. Boil pork cubes. 2. Mix with chopped raw onions; chilies; and coriander leaves (Pork Salad)."
Tripura,Mosdeng Serma,https://www.google.com/search?tbm=isch&q=Mosdeng+Serma,15 mins,"Red Chilies; Garlic; Tomato; Berma",80 kcal,"1. Roast chilies and garlic. 2. Mash with tomato and fermented fish. 3. Spicy chutney side dish."
Uttar Pradesh,Galouti Kebab,https://www.google.com/search?tbm=isch&q=Galouti+Kebab,60 mins,"Finely Minced Mutton; Raw Papaya; Spices; Rose water",350 kcal,"1. Marinate meat with papaya (tenderizer). 2. Mix secret spices. 3. Shallow fry patties in Ghee. Melts in mouth."
Uttar Pradesh,Tehri,https://www.google.com/search?tbm=isch&q=UP+Tehri,40 mins,"Rice; Potatoes; Cauliflower; Peas; Turmeric",300 kcal,"1. Sauté veggies with spices. 2. Add washed rice and water. 3. Cook until yellow fluffy rice is ready."
Uttar Pradesh,Aloo Bedmi Puri,https://www.google.com/search?tbm=isch&q=Bedmi+Puri+Aloo,50 mins,"Wheat Flour; Urad Dal paste; Potato Curry",450 kcal,"1. Knead dough with urad dal paste. 2. Deep fry pooris. 3. Serve with spicy potato gravy."
Uttar Pradesh,Bharwan Bhindi,https://www.google.com/search?tbm=isch&q=Bharwan+Bhindi,30 mins,"Okra (Ladyfinger); Fennel; Coriander powder; Amchur",200 kcal,"1. Slit okra. 2. Fill with spice mix. 3. Pan fry until cooked and crispy."
Uttar Pradesh,Makhan Malai,https://www.google.com/search?tbm=isch&q=Makhan+Malai+Lucknow,8 hours,"Milk Cream; Saffron; Sugar; Dew (Winter special)",300 kcal,"1. Whip milk cream overnight under the sky. 2. Collect the foam. 3. Serve with saffron and nuts (Nimish)."
Uttarakhand,Kafuli,https://www.google.com/search?tbm=isch&q=Kafuli,35 mins,"Spinach; Fenugreek; Rice paste; Curd",180 kcal,"1. Boil and mash green leaves. 2. Cook with rice paste (thickener). 3. Add curd and temper."
Uttarakhand,Bhatt Ki Churkani,https://www.google.com/search?tbm=isch&q=Bhatt+Ki+Churkani,40 mins,"Black Soybean (Bhatt); Flour; Garlic; Ghee",250 kcal,"1. Roast black soybeans in ghee. 2. Add flour and brown it. 3. Add water and simmer until thick."
Uttarakhand,Aloo Ke Gutke,https://www.google.com/search?tbm=isch&q=Aloo+Ke+Gutke,20 mins,"Boiled Potatoes; Jamboo (Herb); Red Chilies; Coriander",200 kcal,"1. Cut boiled potatoes. 2. Stir fry with Pahadi spices and Jamboo herb. 3. Serve dry with tea."
Uttarakhand,Bal Mithai,https://www.google.com/search?tbm=isch&q=Bal+Mithai,60 mins,"Khoya (Mawa); Cane Sugar; Poppy Seeds",400 kcal,"1. Cook Khoya with sugar until chocolate brown (chocolate fudge like). 2. Cut into cubes. 3. Roll in white poppy seeds."
Uttarakhand,Phanu,https://www.google.com/search?tbm=isch&q=Phanu+Recipe,45 mins,"Gahat Dal (Horse Gram); Ginger; Garlic",220 kcal,"1. Soak and grind dal. 2. Fry some as pancakes; mix rest in water. 3. Boil water mixture; add pancakes and cook."
West Bengal,Macher Jhol,https://www.google.com/search?tbm=isch&q=Macher+Jhol,40 mins,"Rohu Fish; Potato; Tomato; Panch Phoron/Kalonji",280 kcal,"1. Lightly fry fish. 2. Make light gravy with spices and veggies. 3. Simmer fish in gravy."
West Bengal,Kosha Mangsho,https://www.google.com/search?tbm=isch&q=Kosha+Mangsho,90 mins,"Mutton; Mustard Oil; Onions; Yogurt; Sugar",500 kcal,"1. Marinate mutton. 2. Slow cook with caramelized onions and spices for hours until dark and thick."
West Bengal,Luchi Alur Dom,https://www.google.com/search?tbm=isch&q=Luchi+Alur+Dom,45 mins,"Maida (Flour); Potatoes; Spices; Ghee",400 kcal,"1. Make fluffy deep-fried flatbreads (Luchi). 2. Cook spicy potato curry (Alur Dom). 3. Serve together."
West Bengal,Shukto,https://www.google.com/search?tbm=isch&q=Bengali+Shukto,40 mins,"Bitter Gourd; Plantain; Potato; Drumstick; Milk; Poppy Seeds",200 kcal,"1. Fry bitter gourd. 2. Sauté other veggies. 3. Simmer in milk and poppy seed paste. A bitter-sweet starter."
West Bengal,Mishti Doi,https://www.google.com/search?tbm=isch&q=Mishti+Doi,12 hours,"Milk; Sugar/Jaggery; Curd culture",300 kcal,"1. Thicken milk by boiling. 2. Caramelize sugar and add to milk. 3. Add culture and let it set in clay pot overnight."`;

function parseCSV(csv) {
    const lines = csv.split('\n');
    return lines.map(line => {
        if (!line.trim()) return null;
        
        const result = [];
        let current = "";
        let inQuotes = false;
        for (let i = 0; i < line.length; i++) {
            const char = line[i];
            if (char === '"') {
                if (inQuotes && line[i + 1] === '"') {
                    // Escaped quote: "" -> "
                    current += '"';
                    i++; // Skip next quote
                } else {
                    inQuotes = !inQuotes;
                }
            } else if (char === ',' && !inQuotes) {
                result.push(current.trim());
                current = "";
            } else {
                current += char;
            }
        }
        result.push(current.trim());
        
        if (result.length < 7) return null;

        return {
            state: result[0],
            name: result[1],
            image: result[2],
            cookTime: result[3],
            ingredients: result[4],
            calories: result[5],
            steps: result[6]
        };
    }).filter(recipe => recipe !== null);
}

async function migrate() {
    console.log("Starting final comprehensive migration...");
    const recipes = parseCSV(rawData);
    
    try {
        // TRUNCATE with RESTART IDENTITY to ensure IDs start from 1
        console.log("Cleaning table and resetting IDs...");
        await db.execute(sql`TRUNCATE TABLE coustome_recipes RESTART IDENTITY;`);
        
        // Split into chunks if necessary (Drizzle handle large inserts well but good practice)
        const chunkSize = 50;
        for (let i = 0; i < recipes.length; i += chunkSize) {
            const chunk = recipes.slice(i, i + chunkSize);
            await db.insert(coustomeRecipesTable).values(chunk).execute();
            console.log("Inserted chunk " + (Math.floor(i / chunkSize) + 1));
        }
        
        console.log("Migration successful! Total inserted: " + recipes.length + " recipes.");
    } catch (error) {
        console.error("Migration failed:", error);
    }
}

migrate();
